/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package cardano-ledger-core-1.22.0.0 */
#ifndef VERSION_cardano_ledger_core
#define VERSION_cardano_ledger_core "1.22.0.0"
#endif /* VERSION_cardano_ledger_core */
#ifndef MIN_VERSION_cardano_ledger_core
#define MIN_VERSION_cardano_ledger_core(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  22 || \
  (major1) == 1 && (major2) == 22 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_ledger_core */
/* package FailT-0.1.2.0 */
#ifndef VERSION_FailT
#define VERSION_FailT "0.1.2.0"
#endif /* VERSION_FailT */
#ifndef MIN_VERSION_FailT
#define MIN_VERSION_FailT(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 2)
#endif /* MIN_VERSION_FailT */
/* package ImpSpec-0.2.0.0 */
#ifndef VERSION_ImpSpec
#define VERSION_ImpSpec "0.2.0.0"
#endif /* VERSION_ImpSpec */
#ifndef MIN_VERSION_ImpSpec
#define MIN_VERSION_ImpSpec(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_ImpSpec */
/* package QuickCheck-2.18.0.0 */
#ifndef VERSION_QuickCheck
#define VERSION_QuickCheck "2.18.0.0"
#endif /* VERSION_QuickCheck */
#ifndef MIN_VERSION_QuickCheck
#define MIN_VERSION_QuickCheck(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  18 || \
  (major1) == 2 && (major2) == 18 && (minor) <= 0)
#endif /* MIN_VERSION_QuickCheck */
/* package aeson-2.2.5.1 */
#ifndef VERSION_aeson
#define VERSION_aeson "2.2.5.1"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_VERSION_aeson */
/* package aeson-pretty-0.8.11 */
#ifndef VERSION_aeson_pretty
#define VERSION_aeson_pretty "0.8.11"
#endif /* VERSION_aeson_pretty */
#ifndef MIN_VERSION_aeson_pretty
#define MIN_VERSION_aeson_pretty(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 11)
#endif /* MIN_VERSION_aeson_pretty */
/* package base-4.18.3.0 */
#ifndef VERSION_base
#define VERSION_base "4.18.3.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  18 || \
  (major1) == 4 && (major2) == 18 && (minor) <= 3)
#endif /* MIN_VERSION_base */
/* package base16-bytestring-1.0.2.0 */
#ifndef VERSION_base16_bytestring
#define VERSION_base16_bytestring "1.0.2.0"
#endif /* VERSION_base16_bytestring */
#ifndef MIN_VERSION_base16_bytestring
#define MIN_VERSION_base16_bytestring(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_base16_bytestring */
/* package binary-0.8.9.1 */
#ifndef VERSION_binary
#define VERSION_binary "0.8.9.1"
#endif /* VERSION_binary */
#ifndef MIN_VERSION_binary
#define MIN_VERSION_binary(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 9)
#endif /* MIN_VERSION_binary */
/* package bytestring-0.11.5.4 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.11.5.4"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  11 || \
  (major1) == 0 && (major2) == 11 && (minor) <= 5)
#endif /* MIN_VERSION_bytestring */
/* package cardano-base-0.1.6.0 */
#ifndef VERSION_cardano_base
#define VERSION_cardano_base "0.1.6.0"
#endif /* VERSION_cardano_base */
#ifndef MIN_VERSION_cardano_base
#define MIN_VERSION_cardano_base(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 6)
#endif /* MIN_VERSION_cardano_base */
/* package cardano-crypto-class-2.6.0.0 */
#ifndef VERSION_cardano_crypto_class
#define VERSION_cardano_crypto_class "2.6.0.0"
#endif /* VERSION_cardano_crypto_class */
#ifndef MIN_VERSION_cardano_crypto_class
#define MIN_VERSION_cardano_crypto_class(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  6 || \
  (major1) == 2 && (major2) == 6 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_crypto_class */
/* package cardano-crypto-class-2.6.0.0 */
#ifndef VERSION_cardano_crypto_class
#define VERSION_cardano_crypto_class "2.6.0.0"
#endif /* VERSION_cardano_crypto_class */
#ifndef MIN_VERSION_cardano_crypto_class
#define MIN_VERSION_cardano_crypto_class(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  6 || \
  (major1) == 2 && (major2) == 6 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_crypto_class */
/* package cardano-crypto-praos-2.2.4.0 */
#ifndef VERSION_cardano_crypto_praos
#define VERSION_cardano_crypto_praos "2.2.4.0"
#endif /* VERSION_cardano_crypto_praos */
#ifndef MIN_VERSION_cardano_crypto_praos
#define MIN_VERSION_cardano_crypto_praos(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_VERSION_cardano_crypto_praos */
/* package cardano-crypto-wrapper-1.8.0.0 */
#ifndef VERSION_cardano_crypto_wrapper
#define VERSION_cardano_crypto_wrapper "1.8.0.0"
#endif /* VERSION_cardano_crypto_wrapper */
#ifndef MIN_VERSION_cardano_crypto_wrapper
#define MIN_VERSION_cardano_crypto_wrapper(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_crypto_wrapper */
/* package cardano-crypto-wrapper-1.8.0.0 */
#ifndef VERSION_cardano_crypto_wrapper
#define VERSION_cardano_crypto_wrapper "1.8.0.0"
#endif /* VERSION_cardano_crypto_wrapper */
#ifndef MIN_VERSION_cardano_crypto_wrapper
#define MIN_VERSION_cardano_crypto_wrapper(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_crypto_wrapper */
/* package cardano-data-1.4.0.0 */
#ifndef VERSION_cardano_data
#define VERSION_cardano_data "1.4.0.0"
#endif /* VERSION_cardano_data */
#ifndef MIN_VERSION_cardano_data
#define MIN_VERSION_cardano_data(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_data */
/* package cardano-ledger-binary-1.10.0.0 */
#ifndef VERSION_cardano_ledger_binary
#define VERSION_cardano_ledger_binary "1.10.0.0"
#endif /* VERSION_cardano_ledger_binary */
#ifndef MIN_VERSION_cardano_ledger_binary
#define MIN_VERSION_cardano_ledger_binary(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  10 || \
  (major1) == 1 && (major2) == 10 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_ledger_binary */
/* package cardano-ledger-binary-1.10.0.0 */
#ifndef VERSION_cardano_ledger_binary
#define VERSION_cardano_ledger_binary "1.10.0.0"
#endif /* VERSION_cardano_ledger_binary */
#ifndef MIN_VERSION_cardano_ledger_binary
#define MIN_VERSION_cardano_ledger_binary(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  10 || \
  (major1) == 1 && (major2) == 10 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_ledger_binary */
/* package cardano-ledger-byron-1.3.0.1 */
#ifndef VERSION_cardano_ledger_byron
#define VERSION_cardano_ledger_byron "1.3.0.1"
#endif /* VERSION_cardano_ledger_byron */
#ifndef MIN_VERSION_cardano_ledger_byron
#define MIN_VERSION_cardano_ledger_byron(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_ledger_byron */
/* package cardano-ledger-byron-1.3.0.1 */
#ifndef VERSION_cardano_ledger_byron
#define VERSION_cardano_ledger_byron "1.3.0.1"
#endif /* VERSION_cardano_ledger_byron */
#ifndef MIN_VERSION_cardano_ledger_byron
#define MIN_VERSION_cardano_ledger_byron(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_ledger_byron */
/* package cardano-ledger-core-1.22.0.0 */
#ifndef VERSION_cardano_ledger_core
#define VERSION_cardano_ledger_core "1.22.0.0"
#endif /* VERSION_cardano_ledger_core */
#ifndef MIN_VERSION_cardano_ledger_core
#define MIN_VERSION_cardano_ledger_core(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  22 || \
  (major1) == 1 && (major2) == 22 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_ledger_core */
/* package cardano-slotting-0.2.2.0 */
#ifndef VERSION_cardano_slotting
#define VERSION_cardano_slotting "0.2.2.0"
#endif /* VERSION_cardano_slotting */
#ifndef MIN_VERSION_cardano_slotting
#define MIN_VERSION_cardano_slotting(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_cardano_slotting */
/* package cardano-slotting-0.2.2.0 */
#ifndef VERSION_cardano_slotting
#define VERSION_cardano_slotting "0.2.2.0"
#endif /* VERSION_cardano_slotting */
#ifndef MIN_VERSION_cardano_slotting
#define MIN_VERSION_cardano_slotting(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_cardano_slotting */
/* package cardano-strict-containers-0.1.6.0 */
#ifndef VERSION_cardano_strict_containers
#define VERSION_cardano_strict_containers "0.1.6.0"
#endif /* VERSION_cardano_strict_containers */
#ifndef MIN_VERSION_cardano_strict_containers
#define MIN_VERSION_cardano_strict_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 6)
#endif /* MIN_VERSION_cardano_strict_containers */
/* package containers-0.6.7 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.7"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_VERSION_containers */
/* package deepseq-1.4.8.1 */
#ifndef VERSION_deepseq
#define VERSION_deepseq "1.4.8.1"
#endif /* VERSION_deepseq */
#ifndef MIN_VERSION_deepseq
#define MIN_VERSION_deepseq(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 8)
#endif /* MIN_VERSION_deepseq */
/* package generic-random-1.5.0.1 */
#ifndef VERSION_generic_random
#define VERSION_generic_random "1.5.0.1"
#endif /* VERSION_generic_random */
#ifndef MIN_VERSION_generic_random
#define MIN_VERSION_generic_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  5 || \
  (major1) == 1 && (major2) == 5 && (minor) <= 0)
#endif /* MIN_VERSION_generic_random */
/* package genvalidity-1.1.1.0 */
#ifndef VERSION_genvalidity
#define VERSION_genvalidity "1.1.1.0"
#endif /* VERSION_genvalidity */
#ifndef MIN_VERSION_genvalidity
#define MIN_VERSION_genvalidity(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 1)
#endif /* MIN_VERSION_genvalidity */
/* package hedgehog-quickcheck-0.1.1 */
#ifndef VERSION_hedgehog_quickcheck
#define VERSION_hedgehog_quickcheck "0.1.1"
#endif /* VERSION_hedgehog_quickcheck */
#ifndef MIN_VERSION_hedgehog_quickcheck
#define MIN_VERSION_hedgehog_quickcheck(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 1)
#endif /* MIN_VERSION_hedgehog_quickcheck */
/* package hspec-2.11.17 */
#ifndef VERSION_hspec
#define VERSION_hspec "2.11.17"
#endif /* VERSION_hspec */
#ifndef MIN_VERSION_hspec
#define MIN_VERSION_hspec(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  11 || \
  (major1) == 2 && (major2) == 11 && (minor) <= 17)
#endif /* MIN_VERSION_hspec */
/* package hspec-golden-0.2.2.0 */
#ifndef VERSION_hspec_golden
#define VERSION_hspec_golden "0.2.2.0"
#endif /* VERSION_hspec_golden */
#ifndef MIN_VERSION_hspec_golden
#define MIN_VERSION_hspec_golden(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_hspec_golden */
/* package microlens-0.5.0.0 */
#ifndef VERSION_microlens
#define VERSION_microlens "0.5.0.0"
#endif /* VERSION_microlens */
#ifndef MIN_VERSION_microlens
#define MIN_VERSION_microlens(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 0)
#endif /* MIN_VERSION_microlens */
/* package mtl-2.3.1 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.3.1"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  3 || \
  (major1) == 2 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_mtl */
/* package nothunks-0.3.1 */
#ifndef VERSION_nothunks
#define VERSION_nothunks "0.3.1"
#endif /* VERSION_nothunks */
#ifndef MIN_VERSION_nothunks
#define MIN_VERSION_nothunks(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_nothunks */
/* package plutus-ledger-api-1.71.0.0 */
#ifndef VERSION_plutus_ledger_api
#define VERSION_plutus_ledger_api "1.71.0.0"
#endif /* VERSION_plutus_ledger_api */
#ifndef MIN_VERSION_plutus_ledger_api
#define MIN_VERSION_plutus_ledger_api(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  71 || \
  (major1) == 1 && (major2) == 71 && (minor) <= 0)
#endif /* MIN_VERSION_plutus_ledger_api */
/* package plutus-ledger-api-1.71.0.0 */
#ifndef VERSION_plutus_ledger_api
#define VERSION_plutus_ledger_api "1.71.0.0"
#endif /* VERSION_plutus_ledger_api */
#ifndef MIN_VERSION_plutus_ledger_api
#define MIN_VERSION_plutus_ledger_api(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  71 || \
  (major1) == 1 && (major2) == 71 && (minor) <= 0)
#endif /* MIN_VERSION_plutus_ledger_api */
/* package prettyprinter-1.7.2 */
#ifndef VERSION_prettyprinter
#define VERSION_prettyprinter "1.7.2"
#endif /* VERSION_prettyprinter */
#ifndef MIN_VERSION_prettyprinter
#define MIN_VERSION_prettyprinter(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  7 || \
  (major1) == 1 && (major2) == 7 && (minor) <= 2)
#endif /* MIN_VERSION_prettyprinter */
/* package primitive-0.9.1.0 */
#ifndef VERSION_primitive
#define VERSION_primitive "0.9.1.0"
#endif /* VERSION_primitive */
#ifndef MIN_VERSION_primitive
#define MIN_VERSION_primitive(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 1)
#endif /* MIN_VERSION_primitive */
/* package quickcheck-transformer-0.3.1.3 */
#ifndef VERSION_quickcheck_transformer
#define VERSION_quickcheck_transformer "0.3.1.3"
#endif /* VERSION_quickcheck_transformer */
#ifndef MIN_VERSION_quickcheck_transformer
#define MIN_VERSION_quickcheck_transformer(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_quickcheck_transformer */
/* package random-1.3.1 */
#ifndef VERSION_random
#define VERSION_random "1.3.1"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_random */
/* package small-steps-1.2.0.0 */
#ifndef VERSION_small_steps
#define VERSION_small_steps "1.2.0.0"
#endif /* VERSION_small_steps */
#ifndef MIN_VERSION_small_steps
#define MIN_VERSION_small_steps(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_small_steps */
/* package text-2.1.4 */
#ifndef VERSION_text
#define VERSION_text "2.1.4"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 4)
#endif /* MIN_VERSION_text */
/* package time-1.12.2 */
#ifndef VERSION_time
#define VERSION_time "1.12.2"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  12 || \
  (major1) == 1 && (major2) == 12 && (minor) <= 2)
#endif /* MIN_VERSION_time */
/* package tree-diff-0.4.1 */
#ifndef VERSION_tree_diff
#define VERSION_tree_diff "0.4.1"
#endif /* VERSION_tree_diff */
#ifndef MIN_VERSION_tree_diff
#define MIN_VERSION_tree_diff(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 1)
#endif /* MIN_VERSION_tree_diff */
/* package unliftio-0.2.25.1 */
#ifndef VERSION_unliftio
#define VERSION_unliftio "0.2.25.1"
#endif /* VERSION_unliftio */
#ifndef MIN_VERSION_unliftio
#define MIN_VERSION_unliftio(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 25)
#endif /* MIN_VERSION_unliftio */
/* package vector-0.13.2.0 */
#ifndef VERSION_vector
#define VERSION_vector "0.13.2.0"
#endif /* VERSION_vector */
#ifndef MIN_VERSION_vector
#define MIN_VERSION_vector(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  13 || \
  (major1) == 0 && (major2) == 13 && (minor) <= 2)
#endif /* MIN_VERSION_vector */
/* package vector-map-1.2.1.0 */
#ifndef VERSION_vector_map
#define VERSION_vector_map "1.2.1.0"
#endif /* VERSION_vector_map */
#ifndef MIN_VERSION_vector_map
#define MIN_VERSION_vector_map(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_vector_map */
/* package vector-map-1.2.1.0 */
#ifndef VERSION_vector_map
#define VERSION_vector_map "1.2.1.0"
#endif /* VERSION_vector_map */
#ifndef MIN_VERSION_vector_map
#define MIN_VERSION_vector_map(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_vector_map */

/* tool alex-3.5.4.2 */
#ifndef TOOL_VERSION_alex
#define TOOL_VERSION_alex "3.5.4.2"
#endif /* TOOL_VERSION_alex */
#ifndef MIN_TOOL_VERSION_alex
#define MIN_TOOL_VERSION_alex(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  5 || \
  (major1) == 3 && (major2) == 5 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_alex */
/* tool gcc-15.2.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "15.2.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  15 || \
  (major1) == 15 && (major2) <  2 || \
  (major1) == 15 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.6.7 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.6.7"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.6.7 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.6.7"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool gpp-15.2.0 */
#ifndef TOOL_VERSION_gpp
#define TOOL_VERSION_gpp "15.2.0"
#endif /* TOOL_VERSION_gpp */
#ifndef MIN_TOOL_VERSION_gpp
#define MIN_TOOL_VERSION_gpp(major1,major2,minor) (\
  (major1) <  15 || \
  (major1) == 15 && (major2) <  2 || \
  (major1) == 15 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gpp */
/* tool haddock-2.29.2 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.29.2"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  29 || \
  (major1) == 2 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool happy-2.2 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "2.2"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_happy */
/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.9 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.9"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 9)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool pkg-config-0.29.2 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.2"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_pkg_config */
/* tool runghc-9.6.7 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.6.7"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_runghc */
/* tool strip-2.44 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.44"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  44 || \
  (major1) == 2 && (major2) == 44 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "cardano-ledger-core-1.22.0.0-inplace-testlib"
#endif /* CURRENT_packageKey */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "cardano-ledger-core-1.22.0.0-inplace-testlib"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "1.22.0.0"
#endif /* CURRENT_PACKAGE_VERSION */
