# @generated by `cabal buck2` from cardano-tracer.cabal - do not edit by hand.
# Re-run `cabal buck2` after editing the .cabal file to refresh this file.

load('//buck2:cabal.bzl', 'cabal_targets')

local_build_spec = {
    'schema': 1,
    'package': {
        'name': 'cardano-tracer',
        'dir': 'packages/cardano-node/cardano-tracer',
    },
    'ghc_options': [
        '-Werror',
    ],
    'components': [
        {
            'kind': 'library',
            'name': 'cardano-tracer',
            'srcs': {
                'Cardano.Tracer.Acceptors.Client': 'src/Cardano/Tracer/Acceptors/Client.hs',
                'Cardano.Tracer.Acceptors.Run': 'src/Cardano/Tracer/Acceptors/Run.hs',
                'Cardano.Tracer.Acceptors.Server': 'src/Cardano/Tracer/Acceptors/Server.hs',
                'Cardano.Tracer.Acceptors.Utils': 'src/Cardano/Tracer/Acceptors/Utils.hs',
                'Cardano.Tracer.Handlers.Logs.File': 'src/Cardano/Tracer/Handlers/Logs/File.hs',
                'Cardano.Tracer.Handlers.Logs.Journal': 'src/Cardano/Tracer/Handlers/Logs/Journal.hs',
                'Cardano.Tracer.Handlers.Logs.Rotator': 'src/Cardano/Tracer/Handlers/Logs/Rotator.hs',
                'Cardano.Tracer.Handlers.Logs.TraceObjects': 'src/Cardano/Tracer/Handlers/Logs/TraceObjects.hs',
                'Cardano.Tracer.Handlers.Logs.Utils': 'src/Cardano/Tracer/Handlers/Logs/Utils.hs',
                'Cardano.Tracer.Handlers.Metrics.Monitoring': 'src/Cardano/Tracer/Handlers/Metrics/Monitoring.hs',
                'Cardano.Tracer.Handlers.Metrics.Prometheus': 'src/Cardano/Tracer/Handlers/Metrics/Prometheus.hs',
                'Cardano.Tracer.Handlers.Metrics.Servers': 'src/Cardano/Tracer/Handlers/Metrics/Servers.hs',
                'Cardano.Tracer.Handlers.Metrics.TimeseriesServer': 'src/Cardano/Tracer/Handlers/Metrics/TimeseriesServer.hs',
                'Cardano.Tracer.Handlers.Metrics.Utils': 'src/Cardano/Tracer/Handlers/Metrics/Utils.hs',
                'Cardano.Tracer.Handlers.Notifications.Check': 'src/Cardano/Tracer/Handlers/Notifications/Check.hs',
                'Cardano.Tracer.Handlers.Notifications.Email': 'src/Cardano/Tracer/Handlers/Notifications/Email.hs',
                'Cardano.Tracer.Handlers.Notifications.Send': 'src/Cardano/Tracer/Handlers/Notifications/Send.hs',
                'Cardano.Tracer.Handlers.Notifications.Settings': 'src/Cardano/Tracer/Handlers/Notifications/Settings.hs',
                'Cardano.Tracer.Handlers.Notifications.Types': 'src/Cardano/Tracer/Handlers/Notifications/Types.hs',
                'Cardano.Tracer.Handlers.Notifications.Utils': 'src/Cardano/Tracer/Handlers/Notifications/Utils.hs',
                'Cardano.Tracer.Handlers.ReForwarder': 'src/Cardano/Tracer/Handlers/ReForwarder.hs',
                'Cardano.Tracer.Handlers.State.TraceObjects': 'src/Cardano/Tracer/Handlers/State/TraceObjects.hs',
                'Cardano.Tracer.Handlers.System': 'src/Cardano/Tracer/Handlers/System.hs',
                'Cardano.Tracer.Handlers.Utils': 'src/Cardano/Tracer/Handlers/Utils.hs',
                'Cardano.Tracer.CLI': 'src/Cardano/Tracer/CLI.hs',
                'Cardano.Tracer.Configuration': 'src/Cardano/Tracer/Configuration.hs',
                'Cardano.Tracer.Environment': 'src/Cardano/Tracer/Environment.hs',
                'Cardano.Tracer.MetaTrace': 'src/Cardano/Tracer/MetaTrace.hs',
                'Cardano.Tracer.Run': 'src/Cardano/Tracer/Run.hs',
                'Cardano.Tracer.Types': 'src/Cardano/Tracer/Types.hs',
                'Cardano.Tracer.Utils': 'src/Cardano/Tracer/Utils.hs',
                'Cardano.Tracer.Handlers.Logs.Journal.NoSystemd': 'src/Cardano/Tracer/Handlers/Logs/Journal/NoSystemd.hs',
                'Cardano.Tracer.Handlers.Notifications.Timer': 'src/Cardano/Tracer/Handlers/Notifications/Timer.hs',
                'Cardano.Tracer.Time': 'src/Cardano/Tracer/Time.hs',
                'Paths_cardano_tracer': {
                    'autogen': 'Paths_cardano_tracer',
                },
                'Cardano.Tracer.Handlers.Logs.Journal.Systemd': 'src/Cardano/Tracer/Handlers/Logs/Journal/Systemd.hs',
            },
            'ghc_options': [
                '-Wall',
                '-Wcompat',
                '-Wincomplete-record-updates',
                '-Wincomplete-uni-patterns',
                '-Wno-unticked-promoted-constructors',
                '-Wno-orphans',
                '-Wpartial-fields',
                '-Wredundant-constraints',
                '-Wunused-packages',
            ],
            'cpp_options': [
                '-DSYSTEMD',
            ],
            'language': 'Haskell2010',
            'extensions': [
                'BlockArguments',
                'DerivingStrategies',
                'GeneralizedNewtypeDeriving',
                'ImportQualifiedPost',
                'InstanceSigs',
                'ScopedTypeVariables',
                'StandaloneKindSignatures',
                'TypeApplications',
            ],
            'deps': [
                {
                    'package': 'yaml',
                },
                {
                    'package': 'warp-tls',
                },
                {
                    'package': 'warp',
                },
                {
                    'package': 'wai',
                },
                {
                    'package': 'vector',
                },
                {
                    'package': 'unordered-containers',
                },
                {
                    'package': 'unix',
                },
                {
                    'package': 'trace-resources',
                },
                {
                    'package': 'trace-forward',
                    'dir': 'packages/cardano-node/trace-forward',
                },
                {
                    'package': 'trace-dispatcher',
                },
                {
                    'package': 'time',
                },
                {
                    'package': 'text',
                },
                {
                    'package': 'stm',
                },
                {
                    'package': 'smtp-mail',
                },
                {
                    'package': 'slugify',
                },
                {
                    'package': 'signal',
                },
                {
                    'package': 'ouroboros-network',
                    'library': 'framework',
                    'dir': 'packages/ouroboros-network/ouroboros-network',
                },
                {
                    'package': 'ouroboros-network',
                    'library': 'api',
                    'dir': 'packages/ouroboros-network/ouroboros-network',
                },
                {
                    'package': 'optparse-applicative',
                },
                {
                    'package': 'network-mux',
                },
                {
                    'package': 'network',
                },
                {
                    'package': 'mime-mail',
                },
                {
                    'package': 'libsystemd-journal',
                },
                {
                    'package': 'http-types',
                },
                {
                    'package': 'filepath',
                },
                {
                    'package': 'extra',
                },
                {
                    'package': 'ekg-wai',
                },
                {
                    'package': 'ekg-forward',
                    'dir': 'dist-newstyle/src/ekg-forward-1.3',
                },
                {
                    'package': 'ekg-core',
                },
                {
                    'package': 'directory',
                },
                {
                    'package': 'contra-tracer',
                },
                {
                    'package': 'containers',
                },
                {
                    'package': 'cborg',
                },
                {
                    'package': 'cardano-timeseries-io',
                    'dir': 'packages/cardano-node/bench/cardano-timeseries-io',
                },
                {
                    'package': 'cardano-diffusion',
                    'dir': 'dist-newstyle/src/cardano-diffusion-1.3.0.0',
                },
                {
                    'package': 'bytestring',
                },
                {
                    'package': 'blaze-html',
                },
                {
                    'package': 'bimap',
                },
                {
                    'package': 'base',
                },
                {
                    'package': 'auto-update',
                },
                {
                    'package': 'async',
                },
                {
                    'package': 'aeson',
                },
            ],
        },
        {
            'kind': 'library',
            'name': 'demo-forwarder-lib',
            'srcs': {
                'Cardano.Tracer.Test.Forwarder': 'test/Cardano/Tracer/Test/Forwarder.hs',
                'Cardano.Tracer.Test.TestSetup': 'test/Cardano/Tracer/Test/TestSetup.hs',
                'Cardano.Tracer.Test.Utils': 'test/Cardano/Tracer/Test/Utils.hs',
            },
            'ghc_options': [
                '-Wall',
                '-Wcompat',
                '-Wincomplete-record-updates',
                '-Wincomplete-uni-patterns',
                '-Wno-unticked-promoted-constructors',
                '-Wno-orphans',
                '-Wpartial-fields',
                '-Wredundant-constraints',
                '-Wunused-packages',
            ],
            'cpp_options': [
                '-DSYSTEMD',
            ],
            'language': 'Haskell2010',
            'extensions': [
                'BlockArguments',
                'DerivingStrategies',
                'GeneralizedNewtypeDeriving',
                'ImportQualifiedPost',
                'InstanceSigs',
                'ScopedTypeVariables',
                'StandaloneKindSignatures',
                'TypeApplications',
            ],
            'deps': [
                {
                    'package': 'vector-algorithms',
                },
                {
                    'package': 'vector',
                },
                {
                    'package': 'trace-forward',
                    'dir': 'packages/cardano-node/trace-forward',
                },
                {
                    'package': 'trace-dispatcher',
                },
                {
                    'package': 'time',
                },
                {
                    'package': 'text',
                },
                {
                    'package': 'tasty-quickcheck',
                },
                {
                    'package': 'ouroboros-network',
                    'library': 'framework',
                    'dir': 'packages/ouroboros-network/ouroboros-network',
                },
                {
                    'package': 'ouroboros-network',
                    'library': 'api',
                    'dir': 'packages/ouroboros-network/ouroboros-network',
                },
                {
                    'package': 'optparse-applicative',
                },
                {
                    'package': 'network-mux',
                },
                {
                    'package': 'network',
                },
                {
                    'package': 'generic-data',
                },
                {
                    'package': 'filepath',
                },
                {
                    'package': 'extra',
                },
                {
                    'package': 'ekg-forward',
                    'dir': 'dist-newstyle/src/ekg-forward-1.3',
                },
                {
                    'package': 'ekg-core',
                },
                {
                    'package': 'directory',
                },
                {
                    'package': 'deepseq',
                },
                {
                    'package': 'contra-tracer',
                },
                {
                    'package': 'cborg',
                },
                {
                    'package': 'cardano-tracer',
                    'dir': 'packages/cardano-node/cardano-tracer',
                },
                {
                    'package': 'bytestring',
                },
                {
                    'package': 'base',
                },
                {
                    'package': 'async',
                },
                {
                    'package': 'aeson',
                },
                {
                    'package': 'QuickCheck',
                },
            ],
        },
        {
            'kind': 'library',
            'name': 'demo-acceptor-lib',
            'srcs': {
                'Cardano.Tracer.Test.Acceptor': 'test/Cardano/Tracer/Test/Acceptor.hs',
                'Cardano.Tracer.Test.TestSetup': 'test/Cardano/Tracer/Test/TestSetup.hs',
                'Cardano.Tracer.Test.Utils': 'test/Cardano/Tracer/Test/Utils.hs',
            },
            'ghc_options': [
                '-Wall',
                '-Wcompat',
                '-Wincomplete-record-updates',
                '-Wincomplete-uni-patterns',
                '-Wno-unticked-promoted-constructors',
                '-Wno-orphans',
                '-Wpartial-fields',
                '-Wredundant-constraints',
                '-Wunused-packages',
            ],
            'cpp_options': [
                '-DSYSTEMD',
            ],
            'language': 'Haskell2010',
            'extensions': [
                'BlockArguments',
                'DerivingStrategies',
                'GeneralizedNewtypeDeriving',
                'ImportQualifiedPost',
                'InstanceSigs',
                'ScopedTypeVariables',
                'StandaloneKindSignatures',
                'TypeApplications',
            ],
            'deps': [
                {
                    'package': 'vector-algorithms',
                },
                {
                    'package': 'vector',
                },
                {
                    'package': 'trace-forward',
                    'dir': 'packages/cardano-node/trace-forward',
                },
                {
                    'package': 'trace-dispatcher',
                },
                {
                    'package': 'text',
                },
                {
                    'package': 'tasty-quickcheck',
                },
                {
                    'package': 'stm',
                },
                {
                    'package': 'ouroboros-network',
                    'library': 'api',
                    'dir': 'packages/ouroboros-network/ouroboros-network',
                },
                {
                    'package': 'optparse-applicative',
                },
                {
                    'package': 'generic-data',
                },
                {
                    'package': 'filepath',
                },
                {
                    'package': 'extra',
                },
                {
                    'package': 'containers',
                },
                {
                    'package': 'cardano-tracer',
                    'dir': 'packages/cardano-node/cardano-tracer',
                },
                {
                    'package': 'bytestring',
                },
                {
                    'package': 'base',
                },
                {
                    'package': 'QuickCheck',
                },
            ],
        },
        {
            'kind': 'executable',
            'name': 'cardano-tracer',
            'main_is': 'app/cardano-tracer.hs',
            'srcs': {
                'Paths_cardano_tracer': {
                    'autogen': 'Paths_cardano_tracer',
                },
            },
            'ghc_options': [
                '-Wall',
                '-Wcompat',
                '-Wincomplete-record-updates',
                '-Wincomplete-uni-patterns',
                '-Wno-unticked-promoted-constructors',
                '-Wno-orphans',
                '-Wpartial-fields',
                '-Wredundant-constraints',
                '-Wunused-packages',
                '-threaded',
                '-rtsopts',
                '-with-rtsopts=-T',
            ],
            'cpp_options': [
                '-DSYSTEMD',
            ],
            'language': 'Haskell2010',
            'extensions': [
                'BlockArguments',
                'DerivingStrategies',
                'GeneralizedNewtypeDeriving',
                'ImportQualifiedPost',
                'InstanceSigs',
                'ScopedTypeVariables',
                'StandaloneKindSignatures',
                'TypeApplications',
            ],
            'deps': [
                {
                    'package': 'optparse-applicative',
                },
                {
                    'package': 'cardano-tracer',
                    'dir': 'packages/cardano-node/cardano-tracer',
                },
                {
                    'package': 'base',
                },
            ],
        },
        {
            'kind': 'executable',
            'name': 'demo-forwarder',
            'main_is': 'demo/ssh/forwarder.hs',
            'ghc_options': [
                '-Wall',
                '-Wcompat',
                '-Wincomplete-record-updates',
                '-Wincomplete-uni-patterns',
                '-Wno-unticked-promoted-constructors',
                '-Wno-orphans',
                '-Wpartial-fields',
                '-Wredundant-constraints',
                '-Wunused-packages',
                '-threaded',
                '-rtsopts',
                '-with-rtsopts=-T',
            ],
            'cpp_options': [
                '-DSYSTEMD',
            ],
            'language': 'Haskell2010',
            'extensions': [
                'BlockArguments',
                'DerivingStrategies',
                'GeneralizedNewtypeDeriving',
                'ImportQualifiedPost',
                'InstanceSigs',
                'ScopedTypeVariables',
                'StandaloneKindSignatures',
                'TypeApplications',
            ],
            'deps': [
                {
                    'package': 'trace-dispatcher',
                },
                {
                    'package': 'cardano-tracer',
                    'library': 'demo-forwarder-lib',
                    'dir': 'packages/cardano-node/cardano-tracer',
                },
                {
                    'package': 'base',
                },
            ],
        },
        {
            'kind': 'executable',
            'name': 'demo-acceptor',
            'main_is': 'demo/acceptor.hs',
            'ghc_options': [
                '-Wall',
                '-Wcompat',
                '-Wincomplete-record-updates',
                '-Wincomplete-uni-patterns',
                '-Wno-unticked-promoted-constructors',
                '-Wno-orphans',
                '-Wpartial-fields',
                '-Wredundant-constraints',
                '-Wunused-packages',
                '-threaded',
                '-rtsopts',
                '-with-rtsopts=-T',
            ],
            'cpp_options': [
                '-DSYSTEMD',
            ],
            'language': 'Haskell2010',
            'extensions': [
                'BlockArguments',
                'DerivingStrategies',
                'GeneralizedNewtypeDeriving',
                'ImportQualifiedPost',
                'InstanceSigs',
                'ScopedTypeVariables',
                'StandaloneKindSignatures',
                'TypeApplications',
            ],
            'deps': [
                {
                    'package': 'cardano-tracer',
                    'library': 'demo-acceptor-lib',
                    'dir': 'packages/cardano-node/cardano-tracer',
                },
                {
                    'package': 'base',
                },
            ],
        },
    ],
}

def generated_targets(**kwargs):
    cabal_targets(local_build_spec, **kwargs)
