# @generated by `cabal buck2` from peras-testnet.cabal - do not edit by hand.
# Re-run `cabal buck2` after editing the .cabal file to refresh this file.

load('//buck2:cabal.bzl', 'cabal_targets')

local_build_spec = {
    'schema': 1,
    'package': {
        'name': 'peras-testnet',
        'dir': 'packages/peras-testnet',
    },
    'ghc_options': [
        "-package", "yaml",
        "-package", "vty-unix",
        "-package", "vty",
        "-package", "vector",
        "-package", "text",
        "-package", "streamly-process",
        "-package", "streamly-core",
        "-package", "scotty",
        "-package", "scientific",
        "-package", "optparse-applicative",
        "-package", "mtl",
        "-package", "iproute",
        "-package", "filepath",
        "-package", "directory",
        "-package", "bytestring",
        "-package", "brick",
        "-package", "base",
        "-package", "aeson-pretty",
        "-package", "aeson",
    ],
    'components': [
        {
            'kind': 'executable',
            'name': 'peras-testnet',
            'main_is': './Main.hs',
            'srcs': {
                'Misc': './Misc.hs',
                'Populate': './Populate.hs',
                'Network': './Network.hs',
                'Gov': './Gov.hs',
                'Scenario': './Scenario.hs',
                'Stake': './Stake.hs',
                'JsonFile': './JsonFile.hs',
                'UI': './UI.hs',
                'UI.CommServer': './UI/CommServer.hs',
            },
            'ghc_options': [
                '-Wall',
                '-Wcompat',
                '-Wincomplete-record-updates',
                '-Wincomplete-uni-patterns',
                '-Wredundant-constraints',
                '-Wunused-packages',
                '-threaded',
                '-with-rtsopts=-N',
            ],
            'language': 'Haskell2010',
            'extensions': [
                'BangPatterns',
                'BlockArguments',
                'DataKinds',
                'DeriveAnyClass',
                'DeriveFoldable',
                'DeriveFunctor',
                'DeriveGeneric',
                'DeriveLift',
                'DeriveTraversable',
                'DerivingStrategies',
                'DerivingVia',
                'DuplicateRecordFields',
                'ExplicitForAll',
                'FlexibleContexts',
                'FlexibleInstances',
                'GADTs',
                'GeneralizedNewtypeDeriving',
                'ImportQualifiedPost',
                'LambdaCase',
                'MultiParamTypeClasses',
                'NamedFieldPuns',
                'NumericUnderscores',
                'OverloadedRecordDot',
                'OverloadedStrings',
                'PolyKinds',
                'QuasiQuotes',
                'RecordWildCards',
                'ScopedTypeVariables',
                'StandaloneDeriving',
                'TemplateHaskell',
                'TupleSections',
                'TypeApplications',
                'TypeFamilies',
                'TypeOperators',
                'ViewPatterns',
            ],
            'deps': [
                {
                    'package': 'yaml',
                },
                {
                    'package': 'vty-unix',
                },
                {
                    'package': 'vty',
                },
                {
                    'package': 'vector',
                },
                {
                    'package': 'text',
                },
                {
                    'package': 'streamly-process',
                },
                {
                    'package': 'streamly-core',
                },
                {
                    'package': 'scotty',
                },
                {
                    'package': 'scientific',
                },
                {
                    'package': 'optparse-applicative',
                },
                {
                    'package': 'mtl',
                },
                {
                    'package': 'iproute',
                },
                {
                    'package': 'filepath',
                },
                {
                    'package': 'directory',
                },
                {
                    'package': 'bytestring',
                },
                {
                    'package': 'brick',
                },
                {
                    'package': 'base',
                },
                {
                    'package': 'aeson-pretty',
                },
                {
                    'package': 'aeson',
                },
            ],
        },
    ],
}

def generated_targets(**kwargs):
    cabal_targets(local_build_spec, **kwargs)
