/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package ouroboros-consensus-5.0.0.0 */
#ifndef VERSION_ouroboros_consensus
#define VERSION_ouroboros_consensus "5.0.0.0"
#endif /* VERSION_ouroboros_consensus */
#ifndef MIN_VERSION_ouroboros_consensus
#define MIN_VERSION_ouroboros_consensus(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  0 || \
  (major1) == 5 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_ouroboros_consensus */
/* package QuickCheck-2.18.0.0 */
#ifndef VERSION_QuickCheck
#define VERSION_QuickCheck "2.18.0.0"
#endif /* VERSION_QuickCheck */
#ifndef MIN_VERSION_QuickCheck
#define MIN_VERSION_QuickCheck(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  18 || \
  (major1) == 2 && (major2) == 18 && (minor) <= 0)
#endif /* MIN_VERSION_QuickCheck */
/* package aeson-2.2.5.1 */
#ifndef VERSION_aeson
#define VERSION_aeson "2.2.5.1"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_VERSION_aeson */
/* package base-4.18.3.0 */
#ifndef VERSION_base
#define VERSION_base "4.18.3.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  18 || \
  (major1) == 4 && (major2) == 18 && (minor) <= 3)
#endif /* MIN_VERSION_base */
/* package bifunctors-5.6.3 */
#ifndef VERSION_bifunctors
#define VERSION_bifunctors "5.6.3"
#endif /* VERSION_bifunctors */
#ifndef MIN_VERSION_bifunctors
#define MIN_VERSION_bifunctors(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  6 || \
  (major1) == 5 && (major2) == 6 && (minor) <= 3)
#endif /* MIN_VERSION_bifunctors */
/* package blockio-0.2.1.0 */
#ifndef VERSION_blockio
#define VERSION_blockio "0.2.1.0"
#endif /* VERSION_blockio */
#ifndef MIN_VERSION_blockio
#define MIN_VERSION_blockio(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_blockio */
/* package bytestring-0.11.5.4 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.11.5.4"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  11 || \
  (major1) == 0 && (major2) == 11 && (minor) <= 5)
#endif /* MIN_VERSION_bytestring */
/* package cardano-binary-1.9.1.0 */
#ifndef VERSION_cardano_binary
#define VERSION_cardano_binary "1.9.1.0"
#endif /* VERSION_cardano_binary */
#ifndef MIN_VERSION_cardano_binary
#define MIN_VERSION_cardano_binary(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  9 || \
  (major1) == 1 && (major2) == 9 && (minor) <= 1)
#endif /* MIN_VERSION_cardano_binary */
/* package cardano-crypto-class-2.6.0.0 */
#ifndef VERSION_cardano_crypto_class
#define VERSION_cardano_crypto_class "2.6.0.0"
#endif /* VERSION_cardano_crypto_class */
#ifndef MIN_VERSION_cardano_crypto_class
#define MIN_VERSION_cardano_crypto_class(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  6 || \
  (major1) == 2 && (major2) == 6 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_crypto_class */
/* package cardano-ledger-binary-1.10.0.0 */
#ifndef VERSION_cardano_ledger_binary
#define VERSION_cardano_ledger_binary "1.10.0.0"
#endif /* VERSION_cardano_ledger_binary */
#ifndef MIN_VERSION_cardano_ledger_binary
#define MIN_VERSION_cardano_ledger_binary(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  10 || \
  (major1) == 1 && (major2) == 10 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_ledger_binary */
/* package cardano-ledger-core-1.22.0.0 */
#ifndef VERSION_cardano_ledger_core
#define VERSION_cardano_ledger_core "1.22.0.0"
#endif /* VERSION_cardano_ledger_core */
#ifndef MIN_VERSION_cardano_ledger_core
#define MIN_VERSION_cardano_ledger_core(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  22 || \
  (major1) == 1 && (major2) == 22 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_ledger_core */
/* package cardano-slotting-0.2.2.0 */
#ifndef VERSION_cardano_slotting
#define VERSION_cardano_slotting "0.2.2.0"
#endif /* VERSION_cardano_slotting */
#ifndef MIN_VERSION_cardano_slotting
#define MIN_VERSION_cardano_slotting(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_cardano_slotting */
/* package cardano-slotting-0.2.2.0 */
#ifndef VERSION_cardano_slotting
#define VERSION_cardano_slotting "0.2.2.0"
#endif /* VERSION_cardano_slotting */
#ifndef MIN_VERSION_cardano_slotting
#define MIN_VERSION_cardano_slotting(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_cardano_slotting */
/* package cborg-0.2.10.0 */
#ifndef VERSION_cborg
#define VERSION_cborg "0.2.10.0"
#endif /* VERSION_cborg */
#ifndef MIN_VERSION_cborg
#define MIN_VERSION_cborg(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 10)
#endif /* MIN_VERSION_cborg */
/* package containers-0.6.7 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.7"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_VERSION_containers */
/* package contra-tracer-0.2.1.1 */
#ifndef VERSION_contra_tracer
#define VERSION_contra_tracer "0.2.1.1"
#endif /* VERSION_contra_tracer */
#ifndef MIN_VERSION_contra_tracer
#define MIN_VERSION_contra_tracer(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_contra_tracer */
/* package deepseq-1.4.8.1 */
#ifndef VERSION_deepseq
#define VERSION_deepseq "1.4.8.1"
#endif /* VERSION_deepseq */
#ifndef MIN_VERSION_deepseq
#define MIN_VERSION_deepseq(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 8)
#endif /* MIN_VERSION_deepseq */
/* package direct-sqlite-2.3.29 */
#ifndef VERSION_direct_sqlite
#define VERSION_direct_sqlite "2.3.29"
#endif /* VERSION_direct_sqlite */
#ifndef MIN_VERSION_direct_sqlite
#define MIN_VERSION_direct_sqlite(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  3 || \
  (major1) == 2 && (major2) == 3 && (minor) <= 29)
#endif /* MIN_VERSION_direct_sqlite */
/* package directory-1.3.8.5 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.8.5"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 8)
#endif /* MIN_VERSION_directory */
/* package filepath-1.4.301.0 */
#ifndef VERSION_filepath
#define VERSION_filepath "1.4.301.0"
#endif /* VERSION_filepath */
#ifndef MIN_VERSION_filepath
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 301)
#endif /* MIN_VERSION_filepath */
/* package fs-api-0.4.0.0 */
#ifndef VERSION_fs_api
#define VERSION_fs_api "0.4.0.0"
#endif /* VERSION_fs_api */
#ifndef MIN_VERSION_fs_api
#define MIN_VERSION_fs_api(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 0)
#endif /* MIN_VERSION_fs_api */
/* package fs-sim-0.5.0.1 */
#ifndef VERSION_fs_sim
#define VERSION_fs_sim "0.5.0.1"
#endif /* VERSION_fs_sim */
#ifndef MIN_VERSION_fs_sim
#define MIN_VERSION_fs_sim(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 0)
#endif /* MIN_VERSION_fs_sim */
/* package generics-sop-0.5.1.4 */
#ifndef VERSION_generics_sop
#define VERSION_generics_sop "0.5.1.4"
#endif /* VERSION_generics_sop */
#ifndef MIN_VERSION_generics_sop
#define MIN_VERSION_generics_sop(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 1)
#endif /* MIN_VERSION_generics_sop */
/* package io-classes-1.8.0.1 */
#ifndef VERSION_io_classes
#define VERSION_io_classes "1.8.0.1"
#endif /* VERSION_io_classes */
#ifndef MIN_VERSION_io_classes
#define MIN_VERSION_io_classes(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_VERSION_io_classes */
/* package io-classes-1.8.0.1 */
#ifndef VERSION_io_classes
#define VERSION_io_classes "1.8.0.1"
#endif /* VERSION_io_classes */
#ifndef MIN_VERSION_io_classes
#define MIN_VERSION_io_classes(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_VERSION_io_classes */
/* package io-classes-1.8.0.1 */
#ifndef VERSION_io_classes
#define VERSION_io_classes "1.8.0.1"
#endif /* VERSION_io_classes */
#ifndef MIN_VERSION_io_classes
#define MIN_VERSION_io_classes(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_VERSION_io_classes */
/* package io-sim-1.8.0.1 */
#ifndef VERSION_io_sim
#define VERSION_io_sim "1.8.0.1"
#endif /* VERSION_io_sim */
#ifndef MIN_VERSION_io_sim
#define MIN_VERSION_io_sim(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_VERSION_io_sim */
/* package mempack-0.2.1.0 */
#ifndef VERSION_mempack
#define VERSION_mempack "0.2.1.0"
#endif /* VERSION_mempack */
#ifndef MIN_VERSION_mempack
#define MIN_VERSION_mempack(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_mempack */
/* package mtl-2.3.1 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.3.1"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  3 || \
  (major1) == 2 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_mtl */
/* package nonempty-containers-0.3.6.0 */
#ifndef VERSION_nonempty_containers
#define VERSION_nonempty_containers "0.3.6.0"
#endif /* VERSION_nonempty_containers */
#ifndef MIN_VERSION_nonempty_containers
#define MIN_VERSION_nonempty_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 6)
#endif /* MIN_VERSION_nonempty_containers */
/* package nothunks-0.3.1 */
#ifndef VERSION_nothunks
#define VERSION_nothunks "0.3.1"
#endif /* VERSION_nothunks */
#ifndef MIN_VERSION_nothunks
#define MIN_VERSION_nothunks(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_nothunks */
/* package ouroboros-consensus-5.0.0.0 */
#ifndef VERSION_ouroboros_consensus
#define VERSION_ouroboros_consensus "5.0.0.0"
#endif /* VERSION_ouroboros_consensus */
#ifndef MIN_VERSION_ouroboros_consensus
#define MIN_VERSION_ouroboros_consensus(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  0 || \
  (major1) == 5 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_ouroboros_consensus */
/* package ouroboros-consensus-5.0.0.0 */
#ifndef VERSION_ouroboros_consensus
#define VERSION_ouroboros_consensus "5.0.0.0"
#endif /* VERSION_ouroboros_consensus */
#ifndef MIN_VERSION_ouroboros_consensus
#define MIN_VERSION_ouroboros_consensus(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  0 || \
  (major1) == 5 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_ouroboros_consensus */
/* package ouroboros-consensus-5.0.0.0 */
#ifndef VERSION_ouroboros_consensus
#define VERSION_ouroboros_consensus "5.0.0.0"
#endif /* VERSION_ouroboros_consensus */
#ifndef MIN_VERSION_ouroboros_consensus
#define MIN_VERSION_ouroboros_consensus(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  0 || \
  (major1) == 5 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_ouroboros_consensus */
/* package ouroboros-network-1.3.0.0 */
#ifndef VERSION_ouroboros_network
#define VERSION_ouroboros_network "1.3.0.0"
#endif /* VERSION_ouroboros_network */
#ifndef MIN_VERSION_ouroboros_network
#define MIN_VERSION_ouroboros_network(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_ouroboros_network */
/* package ouroboros-network-1.3.0.0 */
#ifndef VERSION_ouroboros_network
#define VERSION_ouroboros_network "1.3.0.0"
#endif /* VERSION_ouroboros_network */
#ifndef MIN_VERSION_ouroboros_network
#define MIN_VERSION_ouroboros_network(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_ouroboros_network */
/* package ouroboros-network-1.3.0.0 */
#ifndef VERSION_ouroboros_network
#define VERSION_ouroboros_network "1.3.0.0"
#endif /* VERSION_ouroboros_network */
#ifndef MIN_VERSION_ouroboros_network
#define MIN_VERSION_ouroboros_network(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_ouroboros_network */
/* package pretty-show-1.10 */
#ifndef VERSION_pretty_show
#define VERSION_pretty_show "1.10"
#endif /* VERSION_pretty_show */
#ifndef MIN_VERSION_pretty_show
#define MIN_VERSION_pretty_show(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  10 || \
  (major1) == 1 && (major2) == 10 && (minor) <= 0)
#endif /* MIN_VERSION_pretty_show */
/* package quickcheck-dynamic-4.0.1 */
#ifndef VERSION_quickcheck_dynamic
#define VERSION_quickcheck_dynamic "4.0.1"
#endif /* VERSION_quickcheck_dynamic */
#ifndef MIN_VERSION_quickcheck_dynamic
#define MIN_VERSION_quickcheck_dynamic(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  0 || \
  (major1) == 4 && (major2) == 0 && (minor) <= 1)
#endif /* MIN_VERSION_quickcheck_dynamic */
/* package quickcheck-state-machine-0.10.4 */
#ifndef VERSION_quickcheck_state_machine
#define VERSION_quickcheck_state_machine "0.10.4"
#endif /* VERSION_quickcheck_state_machine */
#ifndef MIN_VERSION_quickcheck_state_machine
#define MIN_VERSION_quickcheck_state_machine(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 4)
#endif /* MIN_VERSION_quickcheck_state_machine */
/* package random-1.3.1 */
#ifndef VERSION_random
#define VERSION_random "1.3.1"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_random */
/* package resource-registry-0.4.0.0 */
#ifndef VERSION_resource_registry
#define VERSION_resource_registry "0.4.0.0"
#endif /* VERSION_resource_registry */
#ifndef MIN_VERSION_resource_registry
#define MIN_VERSION_resource_registry(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 0)
#endif /* MIN_VERSION_resource_registry */
/* package serialise-0.2.6.1 */
#ifndef VERSION_serialise
#define VERSION_serialise "0.2.6.1"
#endif /* VERSION_serialise */
#ifndef MIN_VERSION_serialise
#define MIN_VERSION_serialise(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 6)
#endif /* MIN_VERSION_serialise */
/* package tasty-1.5.4 */
#ifndef VERSION_tasty
#define VERSION_tasty "1.5.4"
#endif /* VERSION_tasty */
#ifndef MIN_VERSION_tasty
#define MIN_VERSION_tasty(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  5 || \
  (major1) == 1 && (major2) == 5 && (minor) <= 4)
#endif /* MIN_VERSION_tasty */
/* package tasty-hunit-0.10.2 */
#ifndef VERSION_tasty_hunit
#define VERSION_tasty_hunit "0.10.2"
#endif /* VERSION_tasty_hunit */
#ifndef MIN_VERSION_tasty_hunit
#define MIN_VERSION_tasty_hunit(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 2)
#endif /* MIN_VERSION_tasty_hunit */
/* package tasty-quickcheck-0.11.1 */
#ifndef VERSION_tasty_quickcheck
#define VERSION_tasty_quickcheck "0.11.1"
#endif /* VERSION_tasty_quickcheck */
#ifndef MIN_VERSION_tasty_quickcheck
#define MIN_VERSION_tasty_quickcheck(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  11 || \
  (major1) == 0 && (major2) == 11 && (minor) <= 1)
#endif /* MIN_VERSION_tasty_quickcheck */
/* package temporary-1.3 */
#ifndef VERSION_temporary
#define VERSION_temporary "1.3"
#endif /* VERSION_temporary */
#ifndef MIN_VERSION_temporary
#define MIN_VERSION_temporary(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_temporary */
/* package text-2.1.4 */
#ifndef VERSION_text
#define VERSION_text "2.1.4"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 4)
#endif /* MIN_VERSION_text */
/* package time-1.12.2 */
#ifndef VERSION_time
#define VERSION_time "1.12.2"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  12 || \
  (major1) == 1 && (major2) == 12 && (minor) <= 2)
#endif /* MIN_VERSION_time */
/* package transformers-0.6.1.0 */
#ifndef VERSION_transformers
#define VERSION_transformers "0.6.1.0"
#endif /* VERSION_transformers */
#ifndef MIN_VERSION_transformers
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 1)
#endif /* MIN_VERSION_transformers */
/* package tree-diff-0.4.1 */
#ifndef VERSION_tree_diff
#define VERSION_tree_diff "0.4.1"
#endif /* VERSION_tree_diff */
#ifndef MIN_VERSION_tree_diff
#define MIN_VERSION_tree_diff(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 1)
#endif /* MIN_VERSION_tree_diff */
/* package vector-0.13.2.0 */
#ifndef VERSION_vector
#define VERSION_vector "0.13.2.0"
#endif /* VERSION_vector */
#ifndef MIN_VERSION_vector
#define MIN_VERSION_vector(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  13 || \
  (major1) == 0 && (major2) == 13 && (minor) <= 2)
#endif /* MIN_VERSION_vector */

/* tool alex-3.5.4.2 */
#ifndef TOOL_VERSION_alex
#define TOOL_VERSION_alex "3.5.4.2"
#endif /* TOOL_VERSION_alex */
#ifndef MIN_TOOL_VERSION_alex
#define MIN_TOOL_VERSION_alex(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  5 || \
  (major1) == 3 && (major2) == 5 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_alex */
/* tool gcc-15.2.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "15.2.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  15 || \
  (major1) == 15 && (major2) <  2 || \
  (major1) == 15 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.6.7 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.6.7"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.6.7 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.6.7"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool gpp-15.2.0 */
#ifndef TOOL_VERSION_gpp
#define TOOL_VERSION_gpp "15.2.0"
#endif /* TOOL_VERSION_gpp */
#ifndef MIN_TOOL_VERSION_gpp
#define MIN_TOOL_VERSION_gpp(major1,major2,minor) (\
  (major1) <  15 || \
  (major1) == 15 && (major2) <  2 || \
  (major1) == 15 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gpp */
/* tool haddock-2.29.2 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.29.2"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  29 || \
  (major1) == 2 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool happy-2.2 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "2.2"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_happy */
/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.9 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.9"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 9)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool pkg-config-0.29.2 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.2"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_pkg_config */
/* tool runghc-9.6.7 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.6.7"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_runghc */
/* tool strip-2.44 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.44"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  44 || \
  (major1) == 2 && (major2) == 44 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "ouroboros-consensus-5.0.0.0-inplace-storage-test"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "5.0.0.0"
#endif /* CURRENT_PACKAGE_VERSION */
