/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package cardano-ledger-byron-1.3.0.1 */
#ifndef VERSION_cardano_ledger_byron
#define VERSION_cardano_ledger_byron "1.3.0.1"
#endif /* VERSION_cardano_ledger_byron */
#ifndef MIN_VERSION_cardano_ledger_byron
#define MIN_VERSION_cardano_ledger_byron(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_ledger_byron */
/* package aeson-2.2.5.1 */
#ifndef VERSION_aeson
#define VERSION_aeson "2.2.5.1"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_VERSION_aeson */
/* package base-4.18.3.0 */
#ifndef VERSION_base
#define VERSION_base "4.18.3.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  18 || \
  (major1) == 4 && (major2) == 18 && (minor) <= 3)
#endif /* MIN_VERSION_base */
/* package base58-bytestring-0.1.0 */
#ifndef VERSION_base58_bytestring
#define VERSION_base58_bytestring "0.1.0"
#endif /* VERSION_base58_bytestring */
#ifndef MIN_VERSION_base58_bytestring
#define MIN_VERSION_base58_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_base58_bytestring */
/* package bimap-0.5.0 */
#ifndef VERSION_bimap
#define VERSION_bimap "0.5.0"
#endif /* VERSION_bimap */
#ifndef MIN_VERSION_bimap
#define MIN_VERSION_bimap(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 0)
#endif /* MIN_VERSION_bimap */
/* package binary-0.8.9.1 */
#ifndef VERSION_binary
#define VERSION_binary "0.8.9.1"
#endif /* VERSION_binary */
#ifndef MIN_VERSION_binary
#define MIN_VERSION_binary(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 9)
#endif /* MIN_VERSION_binary */
/* package bytestring-0.11.5.4 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.11.5.4"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  11 || \
  (major1) == 0 && (major2) == 11 && (minor) <= 5)
#endif /* MIN_VERSION_bytestring */
/* package canonical-json-0.6.0.1 */
#ifndef VERSION_canonical_json
#define VERSION_canonical_json "0.6.0.1"
#endif /* VERSION_canonical_json */
#ifndef MIN_VERSION_canonical_json
#define MIN_VERSION_canonical_json(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 0)
#endif /* MIN_VERSION_canonical_json */
/* package cardano-binary-1.9.1.0 */
#ifndef VERSION_cardano_binary
#define VERSION_cardano_binary "1.9.1.0"
#endif /* VERSION_cardano_binary */
#ifndef MIN_VERSION_cardano_binary
#define MIN_VERSION_cardano_binary(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  9 || \
  (major1) == 1 && (major2) == 9 && (minor) <= 1)
#endif /* MIN_VERSION_cardano_binary */
/* package cardano-crypto-1.4.0 */
#ifndef VERSION_cardano_crypto
#define VERSION_cardano_crypto "1.4.0"
#endif /* VERSION_cardano_crypto */
#ifndef MIN_VERSION_cardano_crypto
#define MIN_VERSION_cardano_crypto(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_crypto */
/* package cardano-crypto-wrapper-1.8.0.0 */
#ifndef VERSION_cardano_crypto_wrapper
#define VERSION_cardano_crypto_wrapper "1.8.0.0"
#endif /* VERSION_cardano_crypto_wrapper */
#ifndef MIN_VERSION_cardano_crypto_wrapper
#define MIN_VERSION_cardano_crypto_wrapper(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_crypto_wrapper */
/* package cardano-ledger-binary-1.10.0.0 */
#ifndef VERSION_cardano_ledger_binary
#define VERSION_cardano_ledger_binary "1.10.0.0"
#endif /* VERSION_cardano_ledger_binary */
#ifndef MIN_VERSION_cardano_ledger_binary
#define MIN_VERSION_cardano_ledger_binary(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  10 || \
  (major1) == 1 && (major2) == 10 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_ledger_binary */
/* package cardano-prelude-0.2.2.0 */
#ifndef VERSION_cardano_prelude
#define VERSION_cardano_prelude "0.2.2.0"
#endif /* VERSION_cardano_prelude */
#ifndef MIN_VERSION_cardano_prelude
#define MIN_VERSION_cardano_prelude(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_cardano_prelude */
/* package cborg-0.2.10.0 */
#ifndef VERSION_cborg
#define VERSION_cborg "0.2.10.0"
#endif /* VERSION_cborg */
#ifndef MIN_VERSION_cborg
#define MIN_VERSION_cborg(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 10)
#endif /* MIN_VERSION_cborg */
/* package containers-0.6.7 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.7"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_VERSION_containers */
/* package contra-tracer-0.2.1.1 */
#ifndef VERSION_contra_tracer
#define VERSION_contra_tracer "0.2.1.1"
#endif /* VERSION_contra_tracer */
#ifndef MIN_VERSION_contra_tracer
#define MIN_VERSION_contra_tracer(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_contra_tracer */
/* package crypton-1.1.4 */
#ifndef VERSION_crypton
#define VERSION_crypton "1.1.4"
#endif /* VERSION_crypton */
#ifndef MIN_VERSION_crypton
#define MIN_VERSION_crypton(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 4)
#endif /* MIN_VERSION_crypton */
/* package digest-0.0.2.1.0.0.0.1 */
#ifndef VERSION_digest
#define VERSION_digest "0.0.2.1.0.0.0.1"
#endif /* VERSION_digest */
#ifndef MIN_VERSION_digest
#define MIN_VERSION_digest(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  0 || \
  (major1) == 0 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_digest */
/* package directory-1.3.8.5 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.8.5"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 8)
#endif /* MIN_VERSION_directory */
/* package filepath-1.4.301.0 */
#ifndef VERSION_filepath
#define VERSION_filepath "1.4.301.0"
#endif /* VERSION_filepath */
#ifndef MIN_VERSION_filepath
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 301)
#endif /* MIN_VERSION_filepath */
/* package formatting-7.2.0 */
#ifndef VERSION_formatting
#define VERSION_formatting "7.2.0"
#endif /* VERSION_formatting */
#ifndef MIN_VERSION_formatting
#define MIN_VERSION_formatting(major1,major2,minor) (\
  (major1) <  7 || \
  (major1) == 7 && (major2) <  2 || \
  (major1) == 7 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_formatting */
/* package heapwords-0.1.0.2 */
#ifndef VERSION_heapwords
#define VERSION_heapwords "0.1.0.2"
#endif /* VERSION_heapwords */
#ifndef MIN_VERSION_heapwords
#define MIN_VERSION_heapwords(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_heapwords */
/* package nothunks-0.3.1 */
#ifndef VERSION_nothunks
#define VERSION_nothunks "0.3.1"
#endif /* VERSION_nothunks */
#ifndef MIN_VERSION_nothunks
#define MIN_VERSION_nothunks(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_nothunks */
/* package quiet-0.2 */
#ifndef VERSION_quiet
#define VERSION_quiet "0.2"
#endif /* VERSION_quiet */
#ifndef MIN_VERSION_quiet
#define MIN_VERSION_quiet(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_quiet */
/* package resourcet-1.3.0 */
#ifndef VERSION_resourcet
#define VERSION_resourcet "1.3.0"
#endif /* VERSION_resourcet */
#ifndef MIN_VERSION_resourcet
#define MIN_VERSION_resourcet(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_resourcet */
/* package streaming-0.2.4.0 */
#ifndef VERSION_streaming
#define VERSION_streaming "0.2.4.0"
#endif /* VERSION_streaming */
#ifndef MIN_VERSION_streaming
#define MIN_VERSION_streaming(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_VERSION_streaming */
/* package streaming-binary-0.3.0.1 */
#ifndef VERSION_streaming_binary
#define VERSION_streaming_binary "0.3.0.1"
#endif /* VERSION_streaming_binary */
#ifndef MIN_VERSION_streaming_binary
#define MIN_VERSION_streaming_binary(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_streaming_binary */
/* package streaming-bytestring-0.3.4 */
#ifndef VERSION_streaming_bytestring
#define VERSION_streaming_bytestring "0.3.4"
#endif /* VERSION_streaming_bytestring */
#ifndef MIN_VERSION_streaming_bytestring
#define MIN_VERSION_streaming_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 4)
#endif /* MIN_VERSION_streaming_bytestring */
/* package text-2.1.4 */
#ifndef VERSION_text
#define VERSION_text "2.1.4"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 4)
#endif /* MIN_VERSION_text */
/* package time-1.12.2 */
#ifndef VERSION_time
#define VERSION_time "1.12.2"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  12 || \
  (major1) == 1 && (major2) == 12 && (minor) <= 2)
#endif /* MIN_VERSION_time */
/* package vector-0.13.2.0 */
#ifndef VERSION_vector
#define VERSION_vector "0.13.2.0"
#endif /* VERSION_vector */
#ifndef MIN_VERSION_vector
#define MIN_VERSION_vector(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  13 || \
  (major1) == 0 && (major2) == 13 && (minor) <= 2)
#endif /* MIN_VERSION_vector */

/* tool alex-3.5.4.2 */
#ifndef TOOL_VERSION_alex
#define TOOL_VERSION_alex "3.5.4.2"
#endif /* TOOL_VERSION_alex */
#ifndef MIN_TOOL_VERSION_alex
#define MIN_TOOL_VERSION_alex(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  5 || \
  (major1) == 3 && (major2) == 5 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_alex */
/* tool gcc-15.2.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "15.2.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  15 || \
  (major1) == 15 && (major2) <  2 || \
  (major1) == 15 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.6.7 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.6.7"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.6.7 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.6.7"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool gpp-15.2.0 */
#ifndef TOOL_VERSION_gpp
#define TOOL_VERSION_gpp "15.2.0"
#endif /* TOOL_VERSION_gpp */
#ifndef MIN_TOOL_VERSION_gpp
#define MIN_TOOL_VERSION_gpp(major1,major2,minor) (\
  (major1) <  15 || \
  (major1) == 15 && (major2) <  2 || \
  (major1) == 15 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gpp */
/* tool haddock-2.29.2 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.29.2"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  29 || \
  (major1) == 2 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool happy-2.2 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "2.2"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_happy */
/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.9 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.9"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 9)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool pkg-config-0.29.2 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.2"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_pkg_config */
/* tool runghc-9.6.7 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.6.7"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_runghc */
/* tool strip-2.44 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.44"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  44 || \
  (major1) == 2 && (major2) == 44 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "cardano-ledger-byron-1.3.0.1-inplace"
#endif /* CURRENT_packageKey */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "cardano-ledger-byron-1.3.0.1-inplace"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "1.3.0.1"
#endif /* CURRENT_PACKAGE_VERSION */
