# @generated by `cabal buck2` from non-integral.cabal - do not edit by hand.
# Re-run `cabal buck2` after editing the .cabal file to refresh this file.

load('//buck2:cabal.bzl', 'cabal_targets')

local_build_spec = {
    'schema': 1,
    'package': {
        'name': 'non-integral',
        'dir': 'packages/cardano-ledger/libs/non-integral',
    },
    'ghc_options': [
        '-Werror',
    ],
    'components': [
        {
            'kind': 'library',
            'name': 'non-integral',
            'srcs': {
                'Cardano.Ledger.NonIntegral': 'src/Cardano/Ledger/NonIntegral.hs',
            },
            'ghc_options': [
                '-Wall',
                '-Wcompat',
                '-Wincomplete-record-updates',
                '-Wincomplete-uni-patterns',
                '-Wredundant-constraints',
                '-Wunused-packages',
            ],
            'language': 'Haskell2010',
            'deps': [
                {
                    'package': 'base',
                },
            ],
        },
    ],
}

def generated_targets(**kwargs):
    cabal_targets(local_build_spec, **kwargs)
