# @generated by `cabal buck2` from small-steps.cabal - do not edit by hand.
# Re-run `cabal buck2` after editing the .cabal file to refresh this file.

load('//buck2:cabal.bzl', 'cabal_targets')

local_build_spec = {
    'schema': 1,
    'package': {
        'name': 'small-steps',
        'dir': 'packages/cardano-ledger/libs/small-steps',
    },
    'ghc_options': [
        '-Werror',
    ],
    'components': [
        {
            'kind': 'library',
            'name': 'small-steps',
            'srcs': {
                'Control.Provenance': 'src/Control/Provenance.hs',
                'Control.State.Transition': 'src/Control/State/Transition.hs',
                'Control.State.Transition.Extended': 'src/Control/State/Transition/Extended.hs',
                'Control.State.Transition.Simple': 'src/Control/State/Transition/Simple.hs',
            },
            'ghc_options': [
                '-Wall',
                '-Wcompat',
                '-Wincomplete-record-updates',
                '-Wincomplete-uni-patterns',
                '-Wredundant-constraints',
                '-Wunused-packages',
            ],
            'language': 'Haskell2010',
            'deps': [
                {
                    'package': 'validation-selective',
                },
                {
                    'package': 'transformers',
                },
                {
                    'package': 'text',
                },
                {
                    'package': 'nothunks',
                },
                {
                    'package': 'mtl',
                },
                {
                    'package': 'free',
                },
                {
                    'package': 'data-default',
                },
                {
                    'package': 'containers',
                },
                {
                    'package': 'cardano-strict-containers',
                },
                {
                    'package': 'cardano-data',
                    'dir': 'packages/cardano-ledger/libs/cardano-data',
                },
                {
                    'package': 'base',
                },
                {
                    'package': 'aeson',
                },
            ],
        },
        {
            'kind': 'library',
            'name': 'testlib',
            'srcs': {
                'Test.Control.State.Transition.Generator': 'testlib/Test/Control/State/Transition/Generator.hs',
                'Test.Control.State.Transition.Invalid.Trace': 'testlib/Test/Control/State/Transition/Invalid/Trace.hs',
                'Test.Control.State.Transition.Trace': 'testlib/Test/Control/State/Transition/Trace.hs',
                'Test.Control.State.Transition.Trace.Generator.QuickCheck': 'testlib/Test/Control/State/Transition/Trace/Generator/QuickCheck.hs',
                'Test.Hedgehog.Extra.Manual': 'testlib/Test/Hedgehog/Extra/Manual.hs',
            },
            'ghc_options': [
                '-Wall',
                '-Wcompat',
                '-Wincomplete-record-updates',
                '-Wincomplete-uni-patterns',
                '-Wredundant-constraints',
                '-Wunused-packages',
            ],
            'language': 'Haskell2010',
            'deps': [
                {
                    'package': 'transformers',
                },
                {
                    'package': 'small-steps',
                    'dir': 'packages/cardano-ledger/libs/small-steps',
                },
                {
                    'package': 'nothunks',
                },
                {
                    'package': 'mtl',
                },
                {
                    'package': 'microlens-th',
                },
                {
                    'package': 'microlens',
                },
                {
                    'package': 'hspec',
                },
                {
                    'package': 'hedgehog',
                },
                {
                    'package': 'deepseq',
                },
                {
                    'package': 'cardano-strict-containers',
                },
                {
                    'package': 'cardano-ledger-binary',
                    'library': 'testlib',
                    'dir': 'packages/cardano-ledger/libs/cardano-ledger-binary',
                },
                {
                    'package': 'base',
                },
                {
                    'package': 'QuickCheck',
                },
            ],
        },
    ],
}

def generated_targets(**kwargs):
    cabal_targets(local_build_spec, **kwargs)
