# @generated by `cabal buck2` from vector-map.cabal - do not edit by hand.
# Re-run `cabal buck2` after editing the .cabal file to refresh this file.

load('//buck2:cabal.bzl', 'cabal_targets')

local_build_spec = {
    'schema': 1,
    'package': {
        'name': 'vector-map',
        'dir': 'packages/cardano-ledger/libs/vector-map',
    },
    'ghc_options': [
        '-Werror',
    ],
    'components': [
        {
            'kind': 'library',
            'name': 'vector-map',
            'srcs': {
                'Data.VMap': 'src/Data/VMap.hs',
                'Data.VMap.KVVector': 'src/Data/VMap/KVVector.hs',
            },
            'ghc_options': [
                '-Wall',
                '-Wcompat',
                '-Wincomplete-record-updates',
                '-Wincomplete-uni-patterns',
                '-Wredundant-constraints',
                '-Wunused-packages',
            ],
            'language': 'Haskell2010',
            'deps': [
                {
                    'package': 'vector-algorithms',
                },
                {
                    'package': 'vector',
                },
                {
                    'package': 'primitive',
                },
                {
                    'package': 'nothunks',
                },
                {
                    'package': 'deepseq',
                },
                {
                    'package': 'containers',
                },
                {
                    'package': 'base',
                },
                {
                    'package': 'aeson',
                },
            ],
        },
        {
            'kind': 'library',
            'name': 'testlib',
            'srcs': {
                'Test.Data.VMap.Arbitrary': 'testlib/Test/Data/VMap/Arbitrary.hs',
                'Test.Data.VMap.TreeDiff': 'testlib/Test/Data/VMap/TreeDiff.hs',
            },
            'ghc_options': [
                '-Wall',
                '-Wcompat',
                '-Wincomplete-record-updates',
                '-Wincomplete-uni-patterns',
                '-Wredundant-constraints',
                '-Wpartial-fields',
                '-Wunused-packages',
            ],
            'language': 'Haskell2010',
            'deps': [
                {
                    'package': 'vector-map',
                    'dir': 'packages/cardano-ledger/libs/vector-map',
                },
                {
                    'package': 'vector',
                },
                {
                    'package': 'tree-diff',
                },
                {
                    'package': 'quickcheck-instances',
                },
                {
                    'package': 'base',
                },
                {
                    'package': 'QuickCheck',
                },
            ],
        },
    ],
}

def generated_targets(**kwargs):
    cabal_targets(local_build_spec, **kwargs)
