/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package ouroboros-consensus-5.0.0.0 */
#ifndef VERSION_ouroboros_consensus
#define VERSION_ouroboros_consensus "5.0.0.0"
#endif /* VERSION_ouroboros_consensus */
#ifndef MIN_VERSION_ouroboros_consensus
#define MIN_VERSION_ouroboros_consensus(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  0 || \
  (major1) == 5 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_ouroboros_consensus */
/* package base-4.18.3.0 */
#ifndef VERSION_base
#define VERSION_base "4.18.3.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  18 || \
  (major1) == 4 && (major2) == 18 && (minor) <= 3)
#endif /* MIN_VERSION_base */
/* package cardano-crypto-class-2.6.0.0 */
#ifndef VERSION_cardano_crypto_class
#define VERSION_cardano_crypto_class "2.6.0.0"
#endif /* VERSION_cardano_crypto_class */
#ifndef MIN_VERSION_cardano_crypto_class
#define MIN_VERSION_cardano_crypto_class(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  6 || \
  (major1) == 2 && (major2) == 6 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_crypto_class */
/* package filepath-1.4.301.0 */
#ifndef VERSION_filepath
#define VERSION_filepath "1.4.301.0"
#endif /* VERSION_filepath */
#ifndef MIN_VERSION_filepath
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 301)
#endif /* MIN_VERSION_filepath */
/* package fsnotify-0.4.4.0 */
#ifndef VERSION_fsnotify
#define VERSION_fsnotify "0.4.4.0"
#endif /* VERSION_fsnotify */
#ifndef MIN_VERSION_fsnotify
#define MIN_VERSION_fsnotify(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 4)
#endif /* MIN_VERSION_fsnotify */
/* package mtl-2.3.1 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.3.1"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  3 || \
  (major1) == 2 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_mtl */
/* package optparse-applicative-0.19.0.0 */
#ifndef VERSION_optparse_applicative
#define VERSION_optparse_applicative "0.19.0.0"
#endif /* VERSION_optparse_applicative */
#ifndef MIN_VERSION_optparse_applicative
#define MIN_VERSION_optparse_applicative(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  19 || \
  (major1) == 0 && (major2) == 19 && (minor) <= 0)
#endif /* MIN_VERSION_optparse_applicative */
/* package ouroboros-consensus-5.0.0.0 */
#ifndef VERSION_ouroboros_consensus
#define VERSION_ouroboros_consensus "5.0.0.0"
#endif /* VERSION_ouroboros_consensus */
#ifndef MIN_VERSION_ouroboros_consensus
#define MIN_VERSION_ouroboros_consensus(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  0 || \
  (major1) == 5 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_ouroboros_consensus */
/* package ouroboros-consensus-5.0.0.0 */
#ifndef VERSION_ouroboros_consensus
#define VERSION_ouroboros_consensus "5.0.0.0"
#endif /* VERSION_ouroboros_consensus */
#ifndef MIN_VERSION_ouroboros_consensus
#define MIN_VERSION_ouroboros_consensus(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  0 || \
  (major1) == 5 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_ouroboros_consensus */
/* package ouroboros-consensus-5.0.0.0 */
#ifndef VERSION_ouroboros_consensus
#define VERSION_ouroboros_consensus "5.0.0.0"
#endif /* VERSION_ouroboros_consensus */
#ifndef MIN_VERSION_ouroboros_consensus
#define MIN_VERSION_ouroboros_consensus(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  0 || \
  (major1) == 5 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_ouroboros_consensus */
/* package ouroboros-consensus-5.0.0.0 */
#ifndef VERSION_ouroboros_consensus
#define VERSION_ouroboros_consensus "5.0.0.0"
#endif /* VERSION_ouroboros_consensus */
#ifndef MIN_VERSION_ouroboros_consensus
#define MIN_VERSION_ouroboros_consensus(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  0 || \
  (major1) == 5 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_ouroboros_consensus */
/* package ouroboros-consensus-5.0.0.0 */
#ifndef VERSION_ouroboros_consensus
#define VERSION_ouroboros_consensus "5.0.0.0"
#endif /* VERSION_ouroboros_consensus */
#ifndef MIN_VERSION_ouroboros_consensus
#define MIN_VERSION_ouroboros_consensus(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  0 || \
  (major1) == 5 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_ouroboros_consensus */
/* package text-2.1.4 */
#ifndef VERSION_text
#define VERSION_text "2.1.4"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 4)
#endif /* MIN_VERSION_text */
/* package with-utf8-1.1.0.0 */
#ifndef VERSION_with_utf8
#define VERSION_with_utf8 "1.1.0.0"
#endif /* VERSION_with_utf8 */
#ifndef MIN_VERSION_with_utf8
#define MIN_VERSION_with_utf8(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_with_utf8 */

/* tool alex-3.5.4.2 */
#ifndef TOOL_VERSION_alex
#define TOOL_VERSION_alex "3.5.4.2"
#endif /* TOOL_VERSION_alex */
#ifndef MIN_TOOL_VERSION_alex
#define MIN_TOOL_VERSION_alex(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  5 || \
  (major1) == 3 && (major2) == 5 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_alex */
/* tool gcc-15.2.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "15.2.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  15 || \
  (major1) == 15 && (major2) <  2 || \
  (major1) == 15 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.6.7 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.6.7"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.6.7 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.6.7"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool gpp-15.2.0 */
#ifndef TOOL_VERSION_gpp
#define TOOL_VERSION_gpp "15.2.0"
#endif /* TOOL_VERSION_gpp */
#ifndef MIN_TOOL_VERSION_gpp
#define MIN_TOOL_VERSION_gpp(major1,major2,minor) (\
  (major1) <  15 || \
  (major1) == 15 && (major2) <  2 || \
  (major1) == 15 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gpp */
/* tool haddock-2.29.2 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.29.2"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  29 || \
  (major1) == 2 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool happy-2.2 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "2.2"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_happy */
/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.9 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.9"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 9)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool pkg-config-0.29.2 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.2"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_pkg_config */
/* tool runghc-9.6.7 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.6.7"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_runghc */
/* tool strip-2.44 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.44"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  44 || \
  (major1) == 2 && (major2) == 44 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "ouroboros-consensus-5.0.0.0-inplace-snapshot-converter"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "5.0.0.0"
#endif /* CURRENT_PACKAGE_VERSION */
