# @generated by `cabal buck2` from cardano-ledger-alonzo.cabal - do not edit by hand.
# Re-run `cabal buck2` after editing the .cabal file to refresh this file.

load('//buck2:cabal.bzl', 'cabal_targets')

local_build_spec = {
    'schema': 1,
    'package': {
        'name': 'cardano-ledger-alonzo',
        'dir': 'packages/cardano-ledger/eras/alonzo/impl',
    },
    'ghc_options': [
        '-Werror',
    ],
    'components': [
        {
            'kind': 'library',
            'name': 'cardano-ledger-alonzo',
            'srcs': {
                'Cardano.Ledger.Alonzo': 'src/Cardano/Ledger/Alonzo.hs',
                'Cardano.Ledger.Alonzo.BlockBody': 'src/Cardano/Ledger/Alonzo/BlockBody.hs',
                'Cardano.Ledger.Alonzo.BlockBody.Internal': 'src/Cardano/Ledger/Alonzo/BlockBody/Internal.hs',
                'Cardano.Ledger.Alonzo.Core': 'src/Cardano/Ledger/Alonzo/Core.hs',
                'Cardano.Ledger.Alonzo.Genesis': 'src/Cardano/Ledger/Alonzo/Genesis.hs',
                'Cardano.Ledger.Alonzo.PParams': 'src/Cardano/Ledger/Alonzo/PParams.hs',
                'Cardano.Ledger.Alonzo.Plutus.Context': 'src/Cardano/Ledger/Alonzo/Plutus/Context.hs',
                'Cardano.Ledger.Alonzo.Plutus.Evaluate': 'src/Cardano/Ledger/Alonzo/Plutus/Evaluate.hs',
                'Cardano.Ledger.Alonzo.Plutus.TxInfo': 'src/Cardano/Ledger/Alonzo/Plutus/TxInfo.hs',
                'Cardano.Ledger.Alonzo.Rules': 'src/Cardano/Ledger/Alonzo/Rules.hs',
                'Cardano.Ledger.Alonzo.Scripts': 'src/Cardano/Ledger/Alonzo/Scripts.hs',
                'Cardano.Ledger.Alonzo.State': 'src/Cardano/Ledger/Alonzo/State.hs',
                'Cardano.Ledger.Alonzo.Transition': 'src/Cardano/Ledger/Alonzo/Transition.hs',
                'Cardano.Ledger.Alonzo.Translation': 'src/Cardano/Ledger/Alonzo/Translation.hs',
                'Cardano.Ledger.Alonzo.Tx': 'src/Cardano/Ledger/Alonzo/Tx.hs',
                'Cardano.Ledger.Alonzo.TxAuxData': 'src/Cardano/Ledger/Alonzo/TxAuxData.hs',
                'Cardano.Ledger.Alonzo.TxBody': 'src/Cardano/Ledger/Alonzo/TxBody.hs',
                'Cardano.Ledger.Alonzo.TxOut': 'src/Cardano/Ledger/Alonzo/TxOut.hs',
                'Cardano.Ledger.Alonzo.TxWits': 'src/Cardano/Ledger/Alonzo/TxWits.hs',
                'Cardano.Ledger.Alonzo.UTxO': 'src/Cardano/Ledger/Alonzo/UTxO.hs',
                'Cardano.Ledger.Alonzo.Block': 'src/Cardano/Ledger/Alonzo/Block.hs',
                'Cardano.Ledger.Alonzo.Era': 'src/Cardano/Ledger/Alonzo/Era.hs',
                'Cardano.Ledger.Alonzo.Forecast': 'src/Cardano/Ledger/Alonzo/Forecast.hs',
                'Cardano.Ledger.Alonzo.Rules.Bbody': 'src/Cardano/Ledger/Alonzo/Rules/Bbody.hs',
                'Cardano.Ledger.Alonzo.Rules.Deleg': 'src/Cardano/Ledger/Alonzo/Rules/Deleg.hs',
                'Cardano.Ledger.Alonzo.Rules.Delegs': 'src/Cardano/Ledger/Alonzo/Rules/Delegs.hs',
                'Cardano.Ledger.Alonzo.Rules.Delpl': 'src/Cardano/Ledger/Alonzo/Rules/Delpl.hs',
                'Cardano.Ledger.Alonzo.Rules.Ledger': 'src/Cardano/Ledger/Alonzo/Rules/Ledger.hs',
                'Cardano.Ledger.Alonzo.Rules.Ledgers': 'src/Cardano/Ledger/Alonzo/Rules/Ledgers.hs',
                'Cardano.Ledger.Alonzo.Rules.Pool': 'src/Cardano/Ledger/Alonzo/Rules/Pool.hs',
                'Cardano.Ledger.Alonzo.Rules.Ppup': 'src/Cardano/Ledger/Alonzo/Rules/Ppup.hs',
                'Cardano.Ledger.Alonzo.Rules.Utxo': 'src/Cardano/Ledger/Alonzo/Rules/Utxo.hs',
                'Cardano.Ledger.Alonzo.Rules.Utxos': 'src/Cardano/Ledger/Alonzo/Rules/Utxos.hs',
                'Cardano.Ledger.Alonzo.Rules.Utxow': 'src/Cardano/Ledger/Alonzo/Rules/Utxow.hs',
                'Cardano.Ledger.Alonzo.State.Account': 'src/Cardano/Ledger/Alonzo/State/Account.hs',
                'Cardano.Ledger.Alonzo.State.CertState': 'src/Cardano/Ledger/Alonzo/State/CertState.hs',
                'Cardano.Ledger.Alonzo.State.Stake': 'src/Cardano/Ledger/Alonzo/State/Stake.hs',
                'Cardano.Ledger.Alonzo.TxCert': 'src/Cardano/Ledger/Alonzo/TxCert.hs',
            },
            'ghc_options': [
                '-Wall',
                '-Wcompat',
                '-Wincomplete-record-updates',
                '-Wincomplete-uni-patterns',
                '-Wpartial-fields',
                '-Wunused-packages',
                '-Wredundant-constraints',
            ],
            'language': 'Haskell2010',
            'deps': [
                {
                    'package': 'validation-selective',
                },
                {
                    'package': 'transformers',
                },
                {
                    'package': 'text',
                },
                {
                    'package': 'small-steps',
                    'dir': 'packages/cardano-ledger/libs/small-steps',
                },
                {
                    'package': 'plutus-ledger-api',
                },
                {
                    'package': 'nothunks',
                },
                {
                    'package': 'microlens',
                },
                {
                    'package': 'mempack',
                },
                {
                    'package': 'deepseq',
                },
                {
                    'package': 'data-default',
                },
                {
                    'package': 'containers',
                },
                {
                    'package': 'cardano-strict-containers',
                },
                {
                    'package': 'cardano-slotting',
                },
                {
                    'package': 'cardano-ledger-shelley',
                    'dir': 'packages/cardano-ledger/eras/shelley/impl',
                },
                {
                    'package': 'cardano-ledger-mary',
                    'dir': 'packages/cardano-ledger/eras/mary/impl',
                },
                {
                    'package': 'cardano-ledger-core',
                    'library': 'internal',
                    'dir': 'packages/cardano-ledger/libs/cardano-ledger-core',
                },
                {
                    'package': 'cardano-ledger-core',
                    'dir': 'packages/cardano-ledger/libs/cardano-ledger-core',
                },
                {
                    'package': 'cardano-ledger-binary',
                    'dir': 'packages/cardano-ledger/libs/cardano-ledger-binary',
                },
                {
                    'package': 'cardano-ledger-allegra',
                    'dir': 'packages/cardano-ledger/eras/allegra/impl',
                },
                {
                    'package': 'cardano-data',
                    'dir': 'packages/cardano-ledger/libs/cardano-data',
                },
                {
                    'package': 'cardano-crypto-class',
                },
                {
                    'package': 'cardano-base',
                },
                {
                    'package': 'bytestring',
                },
                {
                    'package': 'base64-bytestring',
                },
                {
                    'package': 'base',
                },
                {
                    'package': 'aeson',
                },
                {
                    'package': 'FailT',
                },
            ],
        },
        {
            'kind': 'library',
            'name': 'cddl',
            'srcs': {
                'Cardano.Ledger.Alonzo.HuddleSpec': 'cddl/lib/Cardano/Ledger/Alonzo/HuddleSpec.hs',
            },
            'ghc_options': [
                '-Wall',
                '-Wcompat',
                '-Wincomplete-record-updates',
                '-Wincomplete-uni-patterns',
                '-Wredundant-constraints',
                '-Wpartial-fields',
                '-Wunused-packages',
            ],
            'language': 'Haskell2010',
            'deps': [
                {
                    'package': 'heredoc',
                },
                {
                    'package': 'cardano-ledger-mary',
                    'library': 'cddl',
                    'dir': 'packages/cardano-ledger/eras/mary/impl',
                },
                {
                    'package': 'cardano-ledger-core',
                    'library': 'cddl',
                    'dir': 'packages/cardano-ledger/libs/cardano-ledger-core',
                },
                {
                    'package': 'cardano-ledger-alonzo',
                    'dir': 'packages/cardano-ledger/eras/alonzo/impl',
                },
                {
                    'package': 'base',
                },
            ],
        },
        {
            'kind': 'library',
            'name': 'testlib',
            'srcs': {
                'Test.Cardano.Ledger.Alonzo.Arbitrary': 'testlib/Test/Cardano/Ledger/Alonzo/Arbitrary.hs',
                'Test.Cardano.Ledger.Alonzo.Binary.Annotator': 'testlib/Test/Cardano/Ledger/Alonzo/Binary/Annotator.hs',
                'Test.Cardano.Ledger.Alonzo.Binary.Cddl': 'testlib/Test/Cardano/Ledger/Alonzo/Binary/Cddl.hs',
                'Test.Cardano.Ledger.Alonzo.Binary.CostModelsSpec': 'testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs',
                'Test.Cardano.Ledger.Alonzo.Binary.Golden': 'testlib/Test/Cardano/Ledger/Alonzo/Binary/Golden.hs',
                'Test.Cardano.Ledger.Alonzo.Binary.RoundTrip': 'testlib/Test/Cardano/Ledger/Alonzo/Binary/RoundTrip.hs',
                'Test.Cardano.Ledger.Alonzo.Binary.Twiddle': 'testlib/Test/Cardano/Ledger/Alonzo/Binary/Twiddle.hs',
                'Test.Cardano.Ledger.Alonzo.Binary.TxWitsSpec': 'testlib/Test/Cardano/Ledger/Alonzo/Binary/TxWitsSpec.hs',
                'Test.Cardano.Ledger.Alonzo.Era': 'testlib/Test/Cardano/Ledger/Alonzo/Era.hs',
                'Test.Cardano.Ledger.Alonzo.Examples': 'testlib/Test/Cardano/Ledger/Alonzo/Examples.hs',
                'Test.Cardano.Ledger.Alonzo.Imp': 'testlib/Test/Cardano/Ledger/Alonzo/Imp.hs',
                'Test.Cardano.Ledger.Alonzo.Imp.BbodySpec': 'testlib/Test/Cardano/Ledger/Alonzo/Imp/BbodySpec.hs',
                'Test.Cardano.Ledger.Alonzo.Imp.UtxoSpec': 'testlib/Test/Cardano/Ledger/Alonzo/Imp/UtxoSpec.hs',
                'Test.Cardano.Ledger.Alonzo.Imp.UtxosSpec': 'testlib/Test/Cardano/Ledger/Alonzo/Imp/UtxosSpec.hs',
                'Test.Cardano.Ledger.Alonzo.Imp.UtxowSpec': 'testlib/Test/Cardano/Ledger/Alonzo/Imp/UtxowSpec.hs',
                'Test.Cardano.Ledger.Alonzo.Imp.UtxowSpec.Invalid': 'testlib/Test/Cardano/Ledger/Alonzo/Imp/UtxowSpec/Invalid.hs',
                'Test.Cardano.Ledger.Alonzo.Imp.UtxowSpec.Valid': 'testlib/Test/Cardano/Ledger/Alonzo/Imp/UtxowSpec/Valid.hs',
                'Test.Cardano.Ledger.Alonzo.ImpTest': 'testlib/Test/Cardano/Ledger/Alonzo/ImpTest.hs',
                'Test.Cardano.Ledger.Alonzo.Translation.Golden': 'testlib/Test/Cardano/Ledger/Alonzo/Translation/Golden.hs',
                'Test.Cardano.Ledger.Alonzo.Translation.TranslatableGen': 'testlib/Test/Cardano/Ledger/Alonzo/Translation/TranslatableGen.hs',
                'Test.Cardano.Ledger.Alonzo.Translation.TranslationInstance': 'testlib/Test/Cardano/Ledger/Alonzo/Translation/TranslationInstance.hs',
                'Test.Cardano.Ledger.Alonzo.TreeDiff': 'testlib/Test/Cardano/Ledger/Alonzo/TreeDiff.hs',
                'Paths_cardano_ledger_alonzo': {
                    'autogen': 'Paths_cardano_ledger_alonzo',
                },
            },
            'ghc_options': [
                '-Wall',
                '-Wcompat',
                '-Wincomplete-record-updates',
                '-Wincomplete-uni-patterns',
                '-Wpartial-fields',
                '-Wunused-packages',
                '-Wredundant-constraints',
            ],
            'language': 'Haskell2010',
            'deps': [
                {
                    'package': 'tree-diff',
                },
                {
                    'package': 'time',
                },
                {
                    'package': 'text',
                },
                {
                    'package': 'small-steps',
                    'dir': 'packages/cardano-ledger/libs/small-steps',
                },
                {
                    'package': 'serialise',
                },
                {
                    'package': 'plutus-ledger-api',
                },
                {
                    'package': 'mtl',
                },
                {
                    'package': 'microlens-mtl',
                },
                {
                    'package': 'microlens',
                },
                {
                    'package': 'generic-random',
                },
                {
                    'package': 'data-default',
                },
                {
                    'package': 'containers',
                },
                {
                    'package': 'cborg',
                },
                {
                    'package': 'cardano-strict-containers',
                },
                {
                    'package': 'cardano-slotting',
                },
                {
                    'package': 'cardano-ledger-shelley',
                    'library': 'testlib',
                    'dir': 'packages/cardano-ledger/eras/shelley/impl',
                },
                {
                    'package': 'cardano-ledger-shelley',
                    'dir': 'packages/cardano-ledger/eras/shelley/impl',
                },
                {
                    'package': 'cardano-ledger-mary',
                    'library': 'testlib',
                    'dir': 'packages/cardano-ledger/eras/mary/impl',
                },
                {
                    'package': 'cardano-ledger-mary',
                    'dir': 'packages/cardano-ledger/eras/mary/impl',
                },
                {
                    'package': 'cardano-ledger-core',
                    'library': 'testlib',
                    'dir': 'packages/cardano-ledger/libs/cardano-ledger-core',
                },
                {
                    'package': 'cardano-ledger-core',
                    'dir': 'packages/cardano-ledger/libs/cardano-ledger-core',
                },
                {
                    'package': 'cardano-ledger-binary',
                    'library': 'testlib',
                    'dir': 'packages/cardano-ledger/libs/cardano-ledger-binary',
                },
                {
                    'package': 'cardano-ledger-binary',
                    'dir': 'packages/cardano-ledger/libs/cardano-ledger-binary',
                },
                {
                    'package': 'cardano-ledger-alonzo',
                    'dir': 'packages/cardano-ledger/eras/alonzo/impl',
                },
                {
                    'package': 'cardano-ledger-allegra',
                    'library': 'testlib',
                    'dir': 'packages/cardano-ledger/eras/allegra/impl',
                },
                {
                    'package': 'cardano-ledger-allegra',
                    'dir': 'packages/cardano-ledger/eras/allegra/impl',
                },
                {
                    'package': 'cardano-data',
                    'library': 'testlib',
                    'dir': 'packages/cardano-ledger/libs/cardano-data',
                },
                {
                    'package': 'cardano-data',
                    'dir': 'packages/cardano-ledger/libs/cardano-data',
                },
                {
                    'package': 'cardano-base',
                },
                {
                    'package': 'bytestring',
                },
                {
                    'package': 'base',
                },
                {
                    'package': 'HUnit',
                },
            ],
        },
        {
            'kind': 'executable',
            'name': 'generate-cddl',
            'main_is': 'cddl/exe/Main.hs',
            'srcs': {
                'Paths_cardano_ledger_alonzo': {
                    'autogen': 'Paths_cardano_ledger_alonzo',
                },
            },
            'ghc_options': [
                '-Wall',
                '-Wcompat',
                '-Wincomplete-record-updates',
                '-Wincomplete-uni-patterns',
                '-Wredundant-constraints',
                '-Wpartial-fields',
                '-Wunused-packages',
            ],
            'language': 'Haskell2010',
            'deps': [
                {
                    'package': 'cardano-ledger-binary',
                    'library': 'testlib',
                    'dir': 'packages/cardano-ledger/libs/cardano-ledger-binary',
                },
                {
                    'package': 'cardano-ledger-alonzo',
                    'library': 'cddl',
                    'dir': 'packages/cardano-ledger/eras/alonzo/impl',
                },
                {
                    'package': 'base',
                },
            ],
        },
        {
            'kind': 'executable',
            'name': 'gen-golden',
            'main_is': 'test/GenerateGoldenFileMain.hs',
            'srcs': {
                'Paths_cardano_ledger_alonzo': {
                    'autogen': 'Paths_cardano_ledger_alonzo',
                },
            },
            'ghc_options': [
                '-Wall',
                '-Wcompat',
                '-Wincomplete-record-updates',
                '-Wincomplete-uni-patterns',
                '-Wpartial-fields',
                '-Wredundant-constraints',
                '-Wunused-packages',
            ],
            'language': 'Haskell2010',
            'deps': [
                {
                    'package': 'cardano-ledger-alonzo',
                    'library': 'testlib',
                    'dir': 'packages/cardano-ledger/eras/alonzo/impl',
                },
                {
                    'package': 'cardano-ledger-alonzo',
                    'dir': 'packages/cardano-ledger/eras/alonzo/impl',
                },
                {
                    'package': 'base',
                },
            ],
        },
    ],
}

def generated_targets(**kwargs):
    cabal_targets(local_build_spec, **kwargs)
