# @generated by `cabal buck2` from cardano-rpc.cabal - do not edit by hand.
# Re-run `cabal buck2` after editing the .cabal file to refresh this file.

load('//buck2:cabal.bzl', 'cabal_targets')

local_build_spec = {
    'schema': 1,
    'package': {
        'name': 'cardano-rpc',
        'dir': 'packages/cardano-api/cardano-rpc',
    },
    'ghc_options': [
        '-Werror',
    ],
    'components': [
        {
            'kind': 'library',
            'name': 'cardano-rpc',
            'srcs': {
                'Cardano.Rpc.Client': 'src/Cardano/Rpc/Client.hs',
                'Cardano.Rpc.Proto.Api.Node': 'src/Cardano/Rpc/Proto/Api/Node.hs',
                'Cardano.Rpc.Proto.Api.Reflection.V1': 'src/Cardano/Rpc/Proto/Api/Reflection/V1.hs',
                'Cardano.Rpc.Proto.Api.Reflection.V1alpha': 'src/Cardano/Rpc/Proto/Api/Reflection/V1alpha.hs',
                'Cardano.Rpc.Proto.Api.UtxoRpc.Query': 'src/Cardano/Rpc/Proto/Api/UtxoRpc/Query.hs',
                'Cardano.Rpc.Proto.Api.UtxoRpc.Submit': 'src/Cardano/Rpc/Proto/Api/UtxoRpc/Submit.hs',
                'Cardano.Rpc.Proto.Api.UtxoRpc.Sync': 'src/Cardano/Rpc/Proto/Api/UtxoRpc/Sync.hs',
                'Cardano.Rpc.Server': 'src/Cardano/Rpc/Server.hs',
                'Cardano.Rpc.Server.Config': 'src/Cardano/Rpc/Server/Config.hs',
                'Cardano.Rpc.Server.Internal.Env': 'src/Cardano/Rpc/Server/Internal/Env.hs',
                'Cardano.Rpc.Server.Internal.Error': 'src/Cardano/Rpc/Server/Internal/Error.hs',
                'Cardano.Rpc.Server.Internal.Monad': 'src/Cardano/Rpc/Server/Internal/Monad.hs',
                'Cardano.Rpc.Server.Internal.Node': 'src/Cardano/Rpc/Server/Internal/Node.hs',
                'Cardano.Rpc.Server.Internal.Reflection': 'src/Cardano/Rpc/Server/Internal/Reflection.hs',
                'Cardano.Rpc.Server.Internal.Reflection.DescriptorTable': 'src/Cardano/Rpc/Server/Internal/Reflection/DescriptorTable.hs',
                'Cardano.Rpc.Server.Internal.TimedCache': 'src/Cardano/Rpc/Server/Internal/TimedCache.hs',
                'Cardano.Rpc.Server.Internal.Tracing': 'src/Cardano/Rpc/Server/Internal/Tracing.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Eval': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Eval.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Mempool': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Mempool.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Predicate': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Predicate.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Query': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Query.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Submit': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Submit.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Sync': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Sync.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Type': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Type.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Type.BigInt': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Type/BigInt.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Type.Block': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Type/Block.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Type.Byron': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Type/Byron.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Type.Certificate': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Type/Certificate.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Type.ChainPoint': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Type/ChainPoint.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Type.EraSummary': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Type/EraSummary.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Type.Genesis': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Type/Genesis.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Type.Governance': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Type/Governance.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Type.Mempool': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Type/Mempool.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Type.PlutusData': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Type/PlutusData.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Type.ProtocolParameters': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Type/ProtocolParameters.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Type.Rational': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Type/Rational.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Type.Script': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Type/Script.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Type.Tx': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Type/Tx.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Type.TxEval': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Type/TxEval.hs',
                'Cardano.Rpc.Server.Internal.UtxoRpc.Type.TxOutput': 'src/Cardano/Rpc/Server/Internal/UtxoRpc/Type/TxOutput.hs',
                'Cardano.Rpc.Server.NodeKernelAccess': 'src/Cardano/Rpc/Server/NodeKernelAccess.hs',
                'Cardano.Rpc.Server.Internal.Orphans': 'src/Cardano/Rpc/Server/Internal/Orphans.hs',
                'Cardano.Rpc.Server.NodeKernelAccess.Internal.Type': 'src/Cardano/Rpc/Server/NodeKernelAccess/Internal/Type.hs',
                'Paths_cardano_rpc': {
                    'autogen': 'Paths_cardano_rpc',
                },
            },
            'ghc_options': [
                '-Wall',
                '-Wcompat',
                '-Wincomplete-record-updates',
                '-Wincomplete-uni-patterns',
                '-Wno-unticked-promoted-constructors',
                '-Wpartial-fields',
                '-Wredundant-constraints',
                '-Wunused-packages',
            ],
            'language': 'Haskell2010',
            'extensions': [
                'ImportQualifiedPost',
                'OverloadedStrings',
            ],
            'deps': [
                {
                    'package': 'time',
                },
                {
                    'package': 'text',
                },
                {
                    'package': 'strict-sop-core',
                },
                {
                    'package': 'stm',
                },
                {
                    'package': 'sop-extras',
                },
                {
                    'package': 'rio',
                },
                {
                    'package': 'random',
                },
                {
                    'package': 'ram',
                },
                {
                    'package': 'proto-lens-protobuf-types',
                },
                {
                    'package': 'proto-lens',
                },
                {
                    'package': 'ouroboros-consensus',
                    'library': 'cardano',
                    'dir': 'packages/ouroboros-consensus',
                },
                {
                    'package': 'ouroboros-consensus',
                    'dir': 'packages/ouroboros-consensus',
                },
                {
                    'package': 'network',
                },
                {
                    'package': 'microlens',
                },
                {
                    'package': 'mempack',
                },
                {
                    'package': 'iproute',
                },
                {
                    'package': 'grpc-spec',
                },
                {
                    'package': 'grapesy',
                },
                {
                    'package': 'generic-data',
                },
                {
                    'package': 'fs-api',
                },
                {
                    'package': 'formatting',
                },
                {
                    'package': 'filepath',
                },
                {
                    'package': 'errors',
                },
                {
                    'package': 'data-default',
                },
                {
                    'package': 'contra-tracer',
                },
                {
                    'package': 'containers',
                },
                {
                    'package': 'cardano-slotting',
                },
                {
                    'package': 'cardano-rpc',
                    'library': 'gen',
                    'dir': 'packages/cardano-api/cardano-rpc',
                },
                {
                    'package': 'cardano-ledger-shelley',
                    'dir': 'packages/cardano-ledger/eras/shelley/impl',
                },
                {
                    'package': 'cardano-ledger-dijkstra',
                    'dir': 'packages/cardano-ledger/eras/dijkstra/impl',
                },
                {
                    'package': 'cardano-ledger-core',
                    'dir': 'packages/cardano-ledger/libs/cardano-ledger-core',
                },
                {
                    'package': 'cardano-ledger-conway',
                    'dir': 'packages/cardano-ledger/eras/conway/impl',
                },
                {
                    'package': 'cardano-ledger-byron',
                    'dir': 'packages/cardano-ledger/eras/byron/ledger/impl',
                },
                {
                    'package': 'cardano-ledger-binary',
                    'dir': 'packages/cardano-ledger/libs/cardano-ledger-binary',
                },
                {
                    'package': 'cardano-ledger-api',
                    'dir': 'packages/cardano-ledger/libs/cardano-ledger-api',
                },
                {
                    'package': 'cardano-ledger-alonzo',
                    'dir': 'packages/cardano-ledger/eras/alonzo/impl',
                },
                {
                    'package': 'cardano-ledger-allegra',
                    'dir': 'packages/cardano-ledger/eras/allegra/impl',
                },
                {
                    'package': 'cardano-crypto-wrapper',
                    'dir': 'packages/cardano-ledger/eras/byron/crypto',
                },
                {
                    'package': 'cardano-crypto-class',
                },
                {
                    'package': 'cardano-crypto',
                },
                {
                    'package': 'cardano-binary',
                },
                {
                    'package': 'cardano-api',
                    'dir': 'packages/cardano-api/cardano-api',
                },
                {
                    'package': 'bytestring',
                },
                {
                    'package': 'base16-bytestring',
                },
                {
                    'package': 'base',
                },
                {
                    'package': 'aeson',
                },
            ],
        },
        {
            'kind': 'library',
            'name': 'gen',
            'srcs': {
                'Proto.Cardano.Rpc.Node': 'gen/Proto/Cardano/Rpc/Node.hs',
                'Proto.Cardano.Rpc.Node_Fields': 'gen/Proto/Cardano/Rpc/Node_Fields.hs',
                'Proto.Grpc.Reflection.V1.Reflection': 'gen/Proto/Grpc/Reflection/V1/Reflection.hs',
                'Proto.Grpc.Reflection.V1.Reflection_Fields': 'gen/Proto/Grpc/Reflection/V1/Reflection_Fields.hs',
                'Proto.Grpc.Reflection.V1alpha.Reflection': 'gen/Proto/Grpc/Reflection/V1alpha/Reflection.hs',
                'Proto.Grpc.Reflection.V1alpha.Reflection_Fields': 'gen/Proto/Grpc/Reflection/V1alpha/Reflection_Fields.hs',
                'Proto.Utxorpc.V1beta.Cardano.Cardano': 'gen/Proto/Utxorpc/V1beta/Cardano/Cardano.hs',
                'Proto.Utxorpc.V1beta.Cardano.Cardano_Fields': 'gen/Proto/Utxorpc/V1beta/Cardano/Cardano_Fields.hs',
                'Proto.Utxorpc.V1beta.Query.Query': 'gen/Proto/Utxorpc/V1beta/Query/Query.hs',
                'Proto.Utxorpc.V1beta.Query.Query_Fields': 'gen/Proto/Utxorpc/V1beta/Query/Query_Fields.hs',
                'Proto.Utxorpc.V1beta.Submit.Submit': 'gen/Proto/Utxorpc/V1beta/Submit/Submit.hs',
                'Proto.Utxorpc.V1beta.Submit.Submit_Fields': 'gen/Proto/Utxorpc/V1beta/Submit/Submit_Fields.hs',
                'Proto.Utxorpc.V1beta.Sync.Sync': 'gen/Proto/Utxorpc/V1beta/Sync/Sync.hs',
                'Proto.Utxorpc.V1beta.Sync.Sync_Fields': 'gen/Proto/Utxorpc/V1beta/Sync/Sync_Fields.hs',
            },
            'ghc_options': [
                '-Wall',
                '-Wcompat',
                '-Wincomplete-record-updates',
                '-Wincomplete-uni-patterns',
                '-Wno-unticked-promoted-constructors',
                '-Wpartial-fields',
                '-Wredundant-constraints',
                '-Wunused-packages',
            ],
            'language': 'Haskell2010',
            'extensions': [
                'ImportQualifiedPost',
                'OverloadedStrings',
            ],
            'deps': [
                {
                    'package': 'proto-lens-runtime',
                },
                {
                    'package': 'proto-lens-protobuf-types',
                },
            ],
        },
    ],
}

def generated_targets(**kwargs):
    cabal_targets(local_build_spec, **kwargs)
