# @generated by `cabal buck2` from cardano-submit-api.cabal - do not edit by hand.
# Re-run `cabal buck2` after editing the .cabal file to refresh this file.

load('//buck2:cabal.bzl', 'cabal_targets')

local_build_spec = {
    'schema': 1,
    'package': {
        'name': 'cardano-submit-api',
        'dir': 'packages/cardano-node/cardano-submit-api',
    },
    'ghc_options': [
        '-Werror',
    ],
    'components': [
        {
            'kind': 'library',
            'name': 'cardano-submit-api',
            'srcs': {
                'Cardano.TxSubmit': 'src/Cardano/TxSubmit.hs',
                'Cardano.TxSubmit.CLI.Parsers': 'src/Cardano/TxSubmit/CLI/Parsers.hs',
                'Cardano.TxSubmit.CLI.Types': 'src/Cardano/TxSubmit/CLI/Types.hs',
                'Cardano.TxSubmit.Metrics': 'src/Cardano/TxSubmit/Metrics.hs',
                'Cardano.TxSubmit.Orphans': 'src/Cardano/TxSubmit/Orphans.hs',
                'Cardano.TxSubmit.Rest.Parsers': 'src/Cardano/TxSubmit/Rest/Parsers.hs',
                'Cardano.TxSubmit.Rest.Types': 'src/Cardano/TxSubmit/Rest/Types.hs',
                'Cardano.TxSubmit.Rest.Web': 'src/Cardano/TxSubmit/Rest/Web.hs',
                'Cardano.TxSubmit.Tracing.TraceSubmitApi': 'src/Cardano/TxSubmit/Tracing/TraceSubmitApi.hs',
                'Cardano.TxSubmit.Types': 'src/Cardano/TxSubmit/Types.hs',
                'Cardano.TxSubmit.Util': 'src/Cardano/TxSubmit/Util.hs',
                'Cardano.TxSubmit.Web': 'src/Cardano/TxSubmit/Web.hs',
            },
            'ghc_options': [
                '-Wall',
                '-Wcompat',
                '-Wincomplete-record-updates',
                '-Wincomplete-uni-patterns',
                '-Wno-all-missed-specialisations',
                '-Wno-missing-import-lists',
                '-Wno-safe',
                '-Wno-unsafe',
                '-Wunused-packages',
                '-fwarn-incomplete-patterns',
                '-fwarn-redundant-constraints',
            ],
            'language': 'Haskell2010',
            'deps': [
                {
                    'package': 'warp',
                },
                {
                    'package': 'transformers-except',
                },
                {
                    'package': 'trace-dispatcher',
                },
                {
                    'package': 'text',
                },
                {
                    'package': 'streaming-commons',
                },
                {
                    'package': 'servant-server',
                },
                {
                    'package': 'servant',
                },
                {
                    'package': 'safe-exceptions',
                },
                {
                    'package': 'prometheus',
                },
                {
                    'package': 'ouroboros-network',
                    'library': 'protocols',
                    'dir': 'packages/ouroboros-network/ouroboros-network',
                },
                {
                    'package': 'ouroboros-consensus',
                    'library': 'cardano',
                    'dir': 'packages/ouroboros-consensus',
                },
                {
                    'package': 'optparse-applicative-fork',
                },
                {
                    'package': 'network',
                },
                {
                    'package': 'mtl',
                },
                {
                    'package': 'http-media',
                },
                {
                    'package': 'ekg-prometheus-adapter',
                },
                {
                    'package': 'ekg-core',
                },
                {
                    'package': 'containers',
                },
                {
                    'package': 'cardano-crypto-class',
                },
                {
                    'package': 'cardano-cli',
                    'dir': 'packages/cardano-cli/cardano-cli',
                },
                {
                    'package': 'cardano-binary',
                },
                {
                    'package': 'cardano-api',
                    'dir': 'packages/cardano-api/cardano-api',
                },
                {
                    'package': 'bytestring',
                },
                {
                    'package': 'base',
                },
                {
                    'package': 'async',
                },
                {
                    'package': 'aeson',
                },
            ],
        },
        {
            'kind': 'executable',
            'name': 'cardano-submit-api',
            'main_is': 'app/Main.hs',
            'srcs': {
                'Paths_cardano_submit_api': {
                    'autogen': 'Paths_cardano_submit_api',
                },
            },
            'ghc_options': [
                '-Wall',
                '-Wcompat',
                '-Wincomplete-record-updates',
                '-Wincomplete-uni-patterns',
                '-Wno-all-missed-specialisations',
                '-Wno-missing-import-lists',
                '-Wno-safe',
                '-Wno-unsafe',
                '-Wunused-packages',
                '-fwarn-incomplete-patterns',
                '-fwarn-redundant-constraints',
                '-threaded',
                '-rtsopts',
                '-with-rtsopts=-T -I0',
            ],
            'language': 'Haskell2010',
            'deps': [
                {
                    'package': 'text',
                },
                {
                    'package': 'optparse-applicative-fork',
                },
                {
                    'package': 'cardano-submit-api',
                    'dir': 'packages/cardano-node/cardano-submit-api',
                },
                {
                    'package': 'cardano-git-rev',
                },
                {
                    'package': 'cardano-crypto-class',
                },
                {
                    'package': 'cardano-cli',
                    'dir': 'packages/cardano-cli/cardano-cli',
                },
                {
                    'package': 'base',
                },
            ],
        },
    ],
}

def generated_targets(**kwargs):
    cabal_targets(local_build_spec, **kwargs)
