# @generated by `cabal buck2` from cardano-crypto-wrapper.cabal - do not edit by hand.
# Re-run `cabal buck2` after editing the .cabal file to refresh this file.

load('//buck2:cabal.bzl', 'cabal_targets')

local_build_spec = {
    'schema': 1,
    'package': {
        'name': 'cardano-crypto-wrapper',
        'dir': 'packages/cardano-ledger/eras/byron/crypto',
    },
    'ghc_options': [
        '-Werror',
    ],
    'components': [
        {
            'kind': 'library',
            'name': 'cardano-crypto-wrapper',
            'srcs': {
                'Cardano.Crypto': 'src/Cardano/Crypto.hs',
                'Cardano.Crypto.Hashing': 'src/Cardano/Crypto/Hashing.hs',
                'Cardano.Crypto.Orphans': 'src/Cardano/Crypto/Orphans.hs',
                'Cardano.Crypto.ProtocolMagic': 'src/Cardano/Crypto/ProtocolMagic.hs',
                'Cardano.Crypto.Random': 'src/Cardano/Crypto/Random.hs',
                'Cardano.Crypto.Raw': 'src/Cardano/Crypto/Raw.hs',
                'Cardano.Crypto.Signing': 'src/Cardano/Crypto/Signing.hs',
                'Cardano.Crypto.Signing.Redeem': 'src/Cardano/Crypto/Signing/Redeem.hs',
                'Cardano.Crypto.Signing.Safe': 'src/Cardano/Crypto/Signing/Safe.hs',
                'Cardano.Crypto.Signing.KeyGen': 'src/Cardano/Crypto/Signing/KeyGen.hs',
                'Cardano.Crypto.Signing.Redeem.Compact': 'src/Cardano/Crypto/Signing/Redeem/Compact.hs',
                'Cardano.Crypto.Signing.Redeem.KeyGen': 'src/Cardano/Crypto/Signing/Redeem/KeyGen.hs',
                'Cardano.Crypto.Signing.Redeem.Signature': 'src/Cardano/Crypto/Signing/Redeem/Signature.hs',
                'Cardano.Crypto.Signing.Redeem.SigningKey': 'src/Cardano/Crypto/Signing/Redeem/SigningKey.hs',
                'Cardano.Crypto.Signing.Redeem.VerificationKey': 'src/Cardano/Crypto/Signing/Redeem/VerificationKey.hs',
                'Cardano.Crypto.Signing.Safe.KeyGen': 'src/Cardano/Crypto/Signing/Safe/KeyGen.hs',
                'Cardano.Crypto.Signing.Safe.PassPhrase': 'src/Cardano/Crypto/Signing/Safe/PassPhrase.hs',
                'Cardano.Crypto.Signing.Safe.SafeSigner': 'src/Cardano/Crypto/Signing/Safe/SafeSigner.hs',
                'Cardano.Crypto.Signing.Signature': 'src/Cardano/Crypto/Signing/Signature.hs',
                'Cardano.Crypto.Signing.SigningKey': 'src/Cardano/Crypto/Signing/SigningKey.hs',
                'Cardano.Crypto.Signing.Tag': 'src/Cardano/Crypto/Signing/Tag.hs',
                'Cardano.Crypto.Signing.VerificationKey': 'src/Cardano/Crypto/Signing/VerificationKey.hs',
            },
            'ghc_options': [
                '-Wall',
                '-Wno-all-missed-specialisations',
                '-Wno-missing-deriving-strategies',
                '-Wno-missing-import-lists',
                '-Wno-missing-safe-haskell-mode',
                '-Wno-prepositive-qualified-module',
                '-Wno-safe',
                '-Wno-unsafe',
                '-Wunused-packages',
            ],
            'language': 'Haskell2010',
            'extensions': [
                'NoImplicitPrelude',
            ],
            'deps': [
                {
                    'package': 'text',
                },
                {
                    'package': 'ram',
                },
                {
                    'package': 'nothunks',
                },
                {
                    'package': 'heapwords',
                },
                {
                    'package': 'formatting',
                },
                {
                    'package': 'deepseq',
                },
                {
                    'package': 'data-default',
                },
                {
                    'package': 'crypton',
                },
                {
                    'package': 'cardano-prelude',
                },
                {
                    'package': 'cardano-ledger-binary',
                    'dir': 'packages/cardano-ledger/libs/cardano-ledger-binary',
                },
                {
                    'package': 'cardano-crypto',
                },
                {
                    'package': 'canonical-json',
                },
                {
                    'package': 'bytestring',
                },
                {
                    'package': 'binary',
                },
                {
                    'package': 'base64-bytestring-type',
                },
                {
                    'package': 'base64-bytestring',
                },
                {
                    'package': 'base16-bytestring',
                },
                {
                    'package': 'base',
                },
                {
                    'package': 'aeson',
                },
            ],
        },
        {
            'kind': 'library',
            'name': 'testlib',
            'srcs': {
                'Test.Cardano.Crypto.CBOR': 'testlib/Test/Cardano/Crypto/CBOR.hs',
                'Test.Cardano.Crypto.Dummy': 'testlib/Test/Cardano/Crypto/Dummy.hs',
                'Test.Cardano.Crypto.Example': 'testlib/Test/Cardano/Crypto/Example.hs',
                'Test.Cardano.Crypto.Gen': 'testlib/Test/Cardano/Crypto/Gen.hs',
                'Test.Cardano.Crypto.Json': 'testlib/Test/Cardano/Crypto/Json.hs',
                'Test.Cardano.Crypto.Orphans': 'testlib/Test/Cardano/Crypto/Orphans.hs',
                'Paths_cardano_crypto_wrapper': {
                    'autogen': 'Paths_cardano_crypto_wrapper',
                },
            },
            'ghc_options': [
                '-Weverything',
                '-Wno-all-missed-specialisations',
                '-Wno-missing-deriving-strategies',
                '-Wno-missing-import-lists',
                '-Wno-missing-safe-haskell-mode',
                '-Wno-prepositive-qualified-module',
                '-Wno-safe',
                '-Wno-unsafe',
                '-Wunused-packages',
            ],
            'language': 'Haskell2010',
            'extensions': [
                'NoImplicitPrelude',
            ],
            'deps': [
                {
                    'package': 'ram',
                },
                {
                    'package': 'hedgehog',
                },
                {
                    'package': 'crypton',
                },
                {
                    'package': 'cardano-prelude-test',
                },
                {
                    'package': 'cardano-prelude',
                },
                {
                    'package': 'cardano-ledger-binary',
                    'library': 'testlib',
                    'dir': 'packages/cardano-ledger/libs/cardano-ledger-binary',
                },
                {
                    'package': 'cardano-ledger-binary',
                    'dir': 'packages/cardano-ledger/libs/cardano-ledger-binary',
                },
                {
                    'package': 'cardano-crypto-wrapper',
                    'dir': 'packages/cardano-ledger/eras/byron/crypto',
                },
                {
                    'package': 'cardano-crypto',
                },
                {
                    'package': 'cardano-binary',
                    'library': 'testlib',
                },
                {
                    'package': 'bytestring',
                },
                {
                    'package': 'base',
                },
            ],
        },
    ],
}

def generated_targets(**kwargs):
    cabal_targets(local_build_spec, **kwargs)
