/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package cardano-tracer-0.5.0 */
#ifndef VERSION_cardano_tracer
#define VERSION_cardano_tracer "0.5.0"
#endif /* VERSION_cardano_tracer */
#ifndef MIN_VERSION_cardano_tracer
#define MIN_VERSION_cardano_tracer(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_tracer */
/* package QuickCheck-2.18.0.0 */
#ifndef VERSION_QuickCheck
#define VERSION_QuickCheck "2.18.0.0"
#endif /* VERSION_QuickCheck */
#ifndef MIN_VERSION_QuickCheck
#define MIN_VERSION_QuickCheck(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  18 || \
  (major1) == 2 && (major2) == 18 && (minor) <= 0)
#endif /* MIN_VERSION_QuickCheck */
/* package aeson-2.2.5.1 */
#ifndef VERSION_aeson
#define VERSION_aeson "2.2.5.1"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_VERSION_aeson */
/* package async-2.2.6 */
#ifndef VERSION_async
#define VERSION_async "2.2.6"
#endif /* VERSION_async */
#ifndef MIN_VERSION_async
#define MIN_VERSION_async(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 6)
#endif /* MIN_VERSION_async */
/* package base-4.18.3.0 */
#ifndef VERSION_base
#define VERSION_base "4.18.3.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  18 || \
  (major1) == 4 && (major2) == 18 && (minor) <= 3)
#endif /* MIN_VERSION_base */
/* package bytestring-0.11.5.4 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.11.5.4"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  11 || \
  (major1) == 0 && (major2) == 11 && (minor) <= 5)
#endif /* MIN_VERSION_bytestring */
/* package cardano-tracer-0.5.0 */
#ifndef VERSION_cardano_tracer
#define VERSION_cardano_tracer "0.5.0"
#endif /* VERSION_cardano_tracer */
#ifndef MIN_VERSION_cardano_tracer
#define MIN_VERSION_cardano_tracer(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_tracer */
/* package cborg-0.2.10.0 */
#ifndef VERSION_cborg
#define VERSION_cborg "0.2.10.0"
#endif /* VERSION_cborg */
#ifndef MIN_VERSION_cborg
#define MIN_VERSION_cborg(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 10)
#endif /* MIN_VERSION_cborg */
/* package containers-0.6.7 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.7"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_VERSION_containers */
/* package contra-tracer-0.2.1.1 */
#ifndef VERSION_contra_tracer
#define VERSION_contra_tracer "0.2.1.1"
#endif /* VERSION_contra_tracer */
#ifndef MIN_VERSION_contra_tracer
#define MIN_VERSION_contra_tracer(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_contra_tracer */
/* package deepseq-1.4.8.1 */
#ifndef VERSION_deepseq
#define VERSION_deepseq "1.4.8.1"
#endif /* VERSION_deepseq */
#ifndef MIN_VERSION_deepseq
#define MIN_VERSION_deepseq(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 8)
#endif /* MIN_VERSION_deepseq */
/* package directory-1.3.8.5 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.8.5"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 8)
#endif /* MIN_VERSION_directory */
/* package ekg-core-0.1.2.0 */
#ifndef VERSION_ekg_core
#define VERSION_ekg_core "0.1.2.0"
#endif /* VERSION_ekg_core */
#ifndef MIN_VERSION_ekg_core
#define MIN_VERSION_ekg_core(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 2)
#endif /* MIN_VERSION_ekg_core */
/* package ekg-forward-1.3 */
#ifndef VERSION_ekg_forward
#define VERSION_ekg_forward "1.3"
#endif /* VERSION_ekg_forward */
#ifndef MIN_VERSION_ekg_forward
#define MIN_VERSION_ekg_forward(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_ekg_forward */
/* package extra-1.8 */
#ifndef VERSION_extra
#define VERSION_extra "1.8"
#endif /* VERSION_extra */
#ifndef MIN_VERSION_extra
#define MIN_VERSION_extra(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_VERSION_extra */
/* package filepath-1.4.301.0 */
#ifndef VERSION_filepath
#define VERSION_filepath "1.4.301.0"
#endif /* VERSION_filepath */
#ifndef MIN_VERSION_filepath
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 301)
#endif /* MIN_VERSION_filepath */
/* package generic-data-1.1.0.2 */
#ifndef VERSION_generic_data
#define VERSION_generic_data "1.1.0.2"
#endif /* VERSION_generic_data */
#ifndef MIN_VERSION_generic_data
#define MIN_VERSION_generic_data(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_generic_data */
/* package network-3.2.9.0 */
#ifndef VERSION_network
#define VERSION_network "3.2.9.0"
#endif /* VERSION_network */
#ifndef MIN_VERSION_network
#define MIN_VERSION_network(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 9)
#endif /* MIN_VERSION_network */
/* package network-mux-0.12.0.0 */
#ifndef VERSION_network_mux
#define VERSION_network_mux "0.12.0.0"
#endif /* VERSION_network_mux */
#ifndef MIN_VERSION_network_mux
#define MIN_VERSION_network_mux(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 0)
#endif /* MIN_VERSION_network_mux */
/* package optparse-applicative-0.19.0.0 */
#ifndef VERSION_optparse_applicative
#define VERSION_optparse_applicative "0.19.0.0"
#endif /* VERSION_optparse_applicative */
#ifndef MIN_VERSION_optparse_applicative
#define MIN_VERSION_optparse_applicative(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  19 || \
  (major1) == 0 && (major2) == 19 && (minor) <= 0)
#endif /* MIN_VERSION_optparse_applicative */
/* package ouroboros-network-1.3.0.0 */
#ifndef VERSION_ouroboros_network
#define VERSION_ouroboros_network "1.3.0.0"
#endif /* VERSION_ouroboros_network */
#ifndef MIN_VERSION_ouroboros_network
#define MIN_VERSION_ouroboros_network(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_ouroboros_network */
/* package ouroboros-network-1.3.0.0 */
#ifndef VERSION_ouroboros_network
#define VERSION_ouroboros_network "1.3.0.0"
#endif /* VERSION_ouroboros_network */
#ifndef MIN_VERSION_ouroboros_network
#define MIN_VERSION_ouroboros_network(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_ouroboros_network */
/* package stm-2.5.1.0 */
#ifndef VERSION_stm
#define VERSION_stm "2.5.1.0"
#endif /* VERSION_stm */
#ifndef MIN_VERSION_stm
#define MIN_VERSION_stm(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  5 || \
  (major1) == 2 && (major2) == 5 && (minor) <= 1)
#endif /* MIN_VERSION_stm */
/* package tasty-1.5.4 */
#ifndef VERSION_tasty
#define VERSION_tasty "1.5.4"
#endif /* VERSION_tasty */
#ifndef MIN_VERSION_tasty
#define MIN_VERSION_tasty(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  5 || \
  (major1) == 1 && (major2) == 5 && (minor) <= 4)
#endif /* MIN_VERSION_tasty */
/* package tasty-quickcheck-0.11.1 */
#ifndef VERSION_tasty_quickcheck
#define VERSION_tasty_quickcheck "0.11.1"
#endif /* VERSION_tasty_quickcheck */
#ifndef MIN_VERSION_tasty_quickcheck
#define MIN_VERSION_tasty_quickcheck(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  11 || \
  (major1) == 0 && (major2) == 11 && (minor) <= 1)
#endif /* MIN_VERSION_tasty_quickcheck */
/* package text-2.1.4 */
#ifndef VERSION_text
#define VERSION_text "2.1.4"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 4)
#endif /* MIN_VERSION_text */
/* package time-1.12.2 */
#ifndef VERSION_time
#define VERSION_time "1.12.2"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  12 || \
  (major1) == 1 && (major2) == 12 && (minor) <= 2)
#endif /* MIN_VERSION_time */
/* package trace-dispatcher-2.13.1 */
#ifndef VERSION_trace_dispatcher
#define VERSION_trace_dispatcher "2.13.1"
#endif /* VERSION_trace_dispatcher */
#ifndef MIN_VERSION_trace_dispatcher
#define MIN_VERSION_trace_dispatcher(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  13 || \
  (major1) == 2 && (major2) == 13 && (minor) <= 1)
#endif /* MIN_VERSION_trace_dispatcher */
/* package trace-forward-2.5.0 */
#ifndef VERSION_trace_forward
#define VERSION_trace_forward "2.5.0"
#endif /* VERSION_trace_forward */
#ifndef MIN_VERSION_trace_forward
#define MIN_VERSION_trace_forward(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  5 || \
  (major1) == 2 && (major2) == 5 && (minor) <= 0)
#endif /* MIN_VERSION_trace_forward */
/* package unix-compat-0.7.4.1 */
#ifndef VERSION_unix_compat
#define VERSION_unix_compat "0.7.4.1"
#endif /* VERSION_unix_compat */
#ifndef MIN_VERSION_unix_compat
#define MIN_VERSION_unix_compat(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 4)
#endif /* MIN_VERSION_unix_compat */
/* package vector-0.13.2.0 */
#ifndef VERSION_vector
#define VERSION_vector "0.13.2.0"
#endif /* VERSION_vector */
#ifndef MIN_VERSION_vector
#define MIN_VERSION_vector(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  13 || \
  (major1) == 0 && (major2) == 13 && (minor) <= 2)
#endif /* MIN_VERSION_vector */
/* package vector-algorithms-0.9.1.0 */
#ifndef VERSION_vector_algorithms
#define VERSION_vector_algorithms "0.9.1.0"
#endif /* VERSION_vector_algorithms */
#ifndef MIN_VERSION_vector_algorithms
#define MIN_VERSION_vector_algorithms(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 1)
#endif /* MIN_VERSION_vector_algorithms */

/* tool alex-3.5.4.2 */
#ifndef TOOL_VERSION_alex
#define TOOL_VERSION_alex "3.5.4.2"
#endif /* TOOL_VERSION_alex */
#ifndef MIN_TOOL_VERSION_alex
#define MIN_TOOL_VERSION_alex(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  5 || \
  (major1) == 3 && (major2) == 5 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_alex */
/* tool gcc-15.2.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "15.2.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  15 || \
  (major1) == 15 && (major2) <  2 || \
  (major1) == 15 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.6.7 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.6.7"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.6.7 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.6.7"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool gpp-15.2.0 */
#ifndef TOOL_VERSION_gpp
#define TOOL_VERSION_gpp "15.2.0"
#endif /* TOOL_VERSION_gpp */
#ifndef MIN_TOOL_VERSION_gpp
#define MIN_TOOL_VERSION_gpp(major1,major2,minor) (\
  (major1) <  15 || \
  (major1) == 15 && (major2) <  2 || \
  (major1) == 15 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gpp */
/* tool haddock-2.29.2 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.29.2"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  29 || \
  (major1) == 2 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool happy-2.2 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "2.2"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_happy */
/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.9 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.9"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 9)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool pkg-config-0.29.2 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.2"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_pkg_config */
/* tool runghc-9.6.7 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.6.7"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_runghc */
/* tool strip-2.44 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.44"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  44 || \
  (major1) == 2 && (major2) == 44 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "cardano-tracer-0.5.0-inplace-cardano-tracer-test"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.5.0"
#endif /* CURRENT_PACKAGE_VERSION */
