/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package ouroboros-consensus-5.0.0.0 */
#ifndef VERSION_ouroboros_consensus
#define VERSION_ouroboros_consensus "5.0.0.0"
#endif /* VERSION_ouroboros_consensus */
#ifndef MIN_VERSION_ouroboros_consensus
#define MIN_VERSION_ouroboros_consensus(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  0 || \
  (major1) == 5 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_ouroboros_consensus */
/* package ansi-terminal-1.1.5 */
#ifndef VERSION_ansi_terminal
#define VERSION_ansi_terminal "1.1.5"
#endif /* VERSION_ansi_terminal */
#ifndef MIN_VERSION_ansi_terminal
#define MIN_VERSION_ansi_terminal(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 5)
#endif /* MIN_VERSION_ansi_terminal */
/* package base-4.18.3.0 */
#ifndef VERSION_base
#define VERSION_base "4.18.3.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  18 || \
  (major1) == 4 && (major2) == 18 && (minor) <= 3)
#endif /* MIN_VERSION_base */
/* package cardano-ledger-binary-1.10.0.0 */
#ifndef VERSION_cardano_ledger_binary
#define VERSION_cardano_ledger_binary "1.10.0.0"
#endif /* VERSION_cardano_ledger_binary */
#ifndef MIN_VERSION_cardano_ledger_binary
#define MIN_VERSION_cardano_ledger_binary(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  10 || \
  (major1) == 1 && (major2) == 10 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_ledger_binary */
/* package cardano-ledger-core-1.22.0.0 */
#ifndef VERSION_cardano_ledger_core
#define VERSION_cardano_ledger_core "1.22.0.0"
#endif /* VERSION_cardano_ledger_core */
#ifndef MIN_VERSION_cardano_ledger_core
#define MIN_VERSION_cardano_ledger_core(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  22 || \
  (major1) == 1 && (major2) == 22 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_ledger_core */
/* package cardano-ledger-shelley-1.20.0.0 */
#ifndef VERSION_cardano_ledger_shelley
#define VERSION_cardano_ledger_shelley "1.20.0.0"
#endif /* VERSION_cardano_ledger_shelley */
#ifndef MIN_VERSION_cardano_ledger_shelley
#define MIN_VERSION_cardano_ledger_shelley(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  20 || \
  (major1) == 1 && (major2) == 20 && (minor) <= 0)
#endif /* MIN_VERSION_cardano_ledger_shelley */
/* package cborg-0.2.10.0 */
#ifndef VERSION_cborg
#define VERSION_cborg "0.2.10.0"
#endif /* VERSION_cborg */
#ifndef MIN_VERSION_cborg
#define MIN_VERSION_cborg(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 10)
#endif /* MIN_VERSION_cborg */
/* package directory-1.3.8.5 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.8.5"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 8)
#endif /* MIN_VERSION_directory */
/* package filepath-1.4.301.0 */
#ifndef VERSION_filepath
#define VERSION_filepath "1.4.301.0"
#endif /* VERSION_filepath */
#ifndef MIN_VERSION_filepath
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 301)
#endif /* MIN_VERSION_filepath */
/* package fs-api-0.4.0.0 */
#ifndef VERSION_fs_api
#define VERSION_fs_api "0.4.0.0"
#endif /* VERSION_fs_api */
#ifndef MIN_VERSION_fs_api
#define MIN_VERSION_fs_api(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 0)
#endif /* MIN_VERSION_fs_api */
/* package microlens-0.5.0.0 */
#ifndef VERSION_microlens
#define VERSION_microlens "0.5.0.0"
#endif /* VERSION_microlens */
#ifndef MIN_VERSION_microlens
#define MIN_VERSION_microlens(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 0)
#endif /* MIN_VERSION_microlens */
/* package mtl-2.3.1 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.3.1"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  3 || \
  (major1) == 2 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_mtl */
/* package ouroboros-consensus-5.0.0.0 */
#ifndef VERSION_ouroboros_consensus
#define VERSION_ouroboros_consensus "5.0.0.0"
#endif /* VERSION_ouroboros_consensus */
#ifndef MIN_VERSION_ouroboros_consensus
#define MIN_VERSION_ouroboros_consensus(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  0 || \
  (major1) == 5 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_ouroboros_consensus */
/* package ouroboros-consensus-5.0.0.0 */
#ifndef VERSION_ouroboros_consensus
#define VERSION_ouroboros_consensus "5.0.0.0"
#endif /* VERSION_ouroboros_consensus */
#ifndef MIN_VERSION_ouroboros_consensus
#define MIN_VERSION_ouroboros_consensus(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  0 || \
  (major1) == 5 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_ouroboros_consensus */
/* package ouroboros-consensus-5.0.0.0 */
#ifndef VERSION_ouroboros_consensus
#define VERSION_ouroboros_consensus "5.0.0.0"
#endif /* VERSION_ouroboros_consensus */
#ifndef MIN_VERSION_ouroboros_consensus
#define MIN_VERSION_ouroboros_consensus(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  0 || \
  (major1) == 5 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_ouroboros_consensus */
/* package random-1.3.1 */
#ifndef VERSION_random
#define VERSION_random "1.3.1"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_random */
/* package serialise-0.2.6.1 */
#ifndef VERSION_serialise
#define VERSION_serialise "0.2.6.1"
#endif /* VERSION_serialise */
#ifndef MIN_VERSION_serialise
#define MIN_VERSION_serialise(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 6)
#endif /* MIN_VERSION_serialise */
/* package sop-core-0.5.0.2 */
#ifndef VERSION_sop_core
#define VERSION_sop_core "0.5.0.2"
#endif /* VERSION_sop_core */
#ifndef MIN_VERSION_sop_core
#define MIN_VERSION_sop_core(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 0)
#endif /* MIN_VERSION_sop_core */
/* package sop-extras-0.4.2.0 */
#ifndef VERSION_sop_extras
#define VERSION_sop_extras "0.4.2.0"
#endif /* VERSION_sop_extras */
#ifndef MIN_VERSION_sop_extras
#define MIN_VERSION_sop_extras(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 2)
#endif /* MIN_VERSION_sop_extras */
/* package strict-sop-core-0.1.4.0 */
#ifndef VERSION_strict_sop_core
#define VERSION_strict_sop_core "0.1.4.0"
#endif /* VERSION_strict_sop_core */
#ifndef MIN_VERSION_strict_sop_core
#define MIN_VERSION_strict_sop_core(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 4)
#endif /* MIN_VERSION_strict_sop_core */
/* package terminal-progress-bar-0.4.2 */
#ifndef VERSION_terminal_progress_bar
#define VERSION_terminal_progress_bar "0.4.2"
#endif /* VERSION_terminal_progress_bar */
#ifndef MIN_VERSION_terminal_progress_bar
#define MIN_VERSION_terminal_progress_bar(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 2)
#endif /* MIN_VERSION_terminal_progress_bar */
/* package text-2.1.4 */
#ifndef VERSION_text
#define VERSION_text "2.1.4"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 4)
#endif /* MIN_VERSION_text */

/* tool alex-3.5.4.2 */
#ifndef TOOL_VERSION_alex
#define TOOL_VERSION_alex "3.5.4.2"
#endif /* TOOL_VERSION_alex */
#ifndef MIN_TOOL_VERSION_alex
#define MIN_TOOL_VERSION_alex(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  5 || \
  (major1) == 3 && (major2) == 5 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_alex */
/* tool gcc-15.2.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "15.2.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  15 || \
  (major1) == 15 && (major2) <  2 || \
  (major1) == 15 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.6.7 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.6.7"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.6.7 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.6.7"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool gpp-15.2.0 */
#ifndef TOOL_VERSION_gpp
#define TOOL_VERSION_gpp "15.2.0"
#endif /* TOOL_VERSION_gpp */
#ifndef MIN_TOOL_VERSION_gpp
#define MIN_TOOL_VERSION_gpp(major1,major2,minor) (\
  (major1) <  15 || \
  (major1) == 15 && (major2) <  2 || \
  (major1) == 15 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gpp */
/* tool haddock-2.29.2 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.29.2"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  29 || \
  (major1) == 2 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool happy-2.2 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "2.2"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_happy */
/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.9 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.9"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 9)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool pkg-config-0.29.2 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.2"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_pkg_config */
/* tool runghc-9.6.7 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.6.7"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_runghc */
/* tool strip-2.44 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.44"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  44 || \
  (major1) == 2 && (major2) == 44 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "ouroboros-consensus-5.0.0.0-inplace-unstable-snapshot-conversion"
#endif /* CURRENT_packageKey */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "ouroboros-consensus-5.0.0.0-inplace-unstable-snapshot-conversion"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "5.0.0.0"
#endif /* CURRENT_PACKAGE_VERSION */
